### ISSUE TITLE
在靶机执行出现的报错。

### ISSUE THREAD

**Issue by klmyssn** [gloxec/CrossC2#10]
./CrossC2-test: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ./CrossC2-test)
./CrossC2-test: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./CrossC2-test)
./CrossC2-test: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by ./CrossC2-test)
./CrossC2-test: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by ./CrossC2-test)

**Comment by gloxec** [comment]
release v0.3 support lower version GLIBC

Update cna, choose **Linux-GLIBC**
