### ISSUE TITLE
CS4.3 CrossC2 2.2.4 无法上线

### ISSUE THREAD

**Issue by crazy0x70** [gloxec/CrossC2#101]
如题，CS4.3 CrossC2 2.2.4 无法上线，靶机下载正常，无法上线
![image](https://user-images.githubusercontent.com/85382711/126931207-f8ccbae8-8e69-44d3-8492-42ea165cfc96.png)

**Comment by gloxec** [comment]
出现`[conf]: alive`代表已经成功和teamserver建立连接，不上线的原因可能是因为你配置了c2profile，但CrossC2在生成时未配置rebind.so
参考: https://github.com/gloxec/CrossC2/issues/74#issuecomment-815025831
