### ISSUE TITLE
https.profile中的疑问

### ISSUE THREAD

**Issue by Richard-Tang** [gloxec/CrossC2#102]
[c2profile.c](https://github.com/gloxec/CrossC2/blob/cs4.1/protocol_demo/c2profile.c)文件中好像没有写对mask的解码，然后protocol_demo里提供的[https.profile](https://github.com/gloxec/CrossC2/blob/cs4.1/protocol_demo/https.profile)中的server output处是有个mask编码的。

![image](https://user-images.githubusercontent.com/30547741/127129120-a78dafc4-ec10-4c9e-b2c1-09a57cc3b9e6.png)

为什么c2profile.c里没写对mask的解码也能正常使用呢？

**Comment by Richard-Tang** [comment]
这里我用自己的profile时候只保留 server { ... output { ... } } 里有mask编码，然后在c2profile.c文件中去切割对应字符，但是不做mask解码，然后是没法正常使用的。但是提供的demo是可以的，不是很明白为什么。

**Comment by gloxec** [comment]
> 用自己的profile时候只保留 server { ... output { ... } } 里有mask编码

你自己的这段是来自http-get中的吧

> 为什么c2profile.c里没写对mask的解码也能正常使用呢

cs的http-post { server通信实际并不需要，所以这里有无都没有影响

**Comment by Richard-Tang** [comment]
> > 用自己的profile时候只保留 server { ... output { ... } } 里有mask编码
> 
> 你自己的这段是来自http-get中的吧
> 
> > 为什么c2profile.c里没写对mask的解码也能正常使用呢
> 
> cs的http-post { server通信实际并不需要，所以这里有无都没有影响

后来我重新试了一下我自己的profile，发现是可以的可能之前哪里搞错了。

server在响应post数据的时候不是应该根据http-post的配置对metadata进行编码吗？这里的不影响是说Beacon收到server响应回来的数据实际上是不作处理的吗？

**Comment by gloxec** [comment]
> server在响应post数据的时候不是应该根据http-post的配置对metadata进行编码吗

实际目前server响应的post包并不带任何有效数据，算是后期保留吧

**Comment by Richard-Tang** [comment]
好的，明白。感谢师傅解答
