### ISSUE TITLE
生成载荷失败

### ISSUE THREAD

**Issue by komomon** [gloxec/CrossC2#104]
CS4.1
[11:10:46] null value error at CrossC2.cna:51
[11:10:46] null value error at CrossC2.cna:51
[11:10:46] null value error at CrossC2.cna:172
![image](https://user-images.githubusercontent.com/52700174/127799668-bf305250-0b7e-4ce3-9719-07cf0d1434f0.png)
![image](https://user-images.githubusercontent.com/52700174/127799678-c5124f4d-d1c7-4617-923f-888db41c6be2.png)
![image](https://user-images.githubusercontent.com/52700174/127799722-c6e173fa-8a7f-4f4a-895d-3474f3de8bb3.png)

查看了一下/usr/bin/uname 是存在的。
![image](https://user-images.githubusercontent.com/52700174/127799709-436602f7-4a34-4378-9546-a877fb160287.png)

**Comment by gloxec** [comment]
> CS4.1
> [11:10:46] null value error at CrossC2.cna:51
> [11:10:46] null value error at CrossC2.cna:51
> [11:10:46] null value error at CrossC2.cna:172

172: $process = exec($genCC2);

这行对应你event界面提示的CrossC2生成命令`/root/..../genCrossC2.Linux ...`也是运行报同样错误，是否尝试过将运行命令复制至终端运行呢？
