### ISSUE TITLE
Dropped HTTP client 

### ISSUE THREAD

**Issue by iloveflag** [gloxec/CrossC2#107]
[-] Dropped HTTP client from /<myvps> (missing URI)
[!] Trapped java.lang.RuntimeException during Script Unix Web Delivery (curl): /a [Manage: neo]: URI /a hosts: page
![image](https://user-images.githubusercontent.com/25424842/129478469-ea4e7208-8032-46ae-abed-e930264cbafc.png)

**Comment by BreakALegCml** [comment]
> [-] Dropped HTTP client from / (missing URI) [!] Trapped java.lang.RuntimeException during Script Unix Web Delivery (curl): /a [Manage: neo]: URI /a hosts: page ![image](https://user-images.githubusercontent.com/25424842/129478469-ea4e7208-8032-46ae-abed-e930264cbafc.png)


你好，请问你知道是什么原因造成的这个现象吗

**Comment by gloxec** [comment]
@iloveflag  @BreakALegCml 很明显是 `/a` 这个URI 重复定义了，换个其他路径即可

**Comment by BreakALegCml** [comment]
> @iloveflag @BreakALegCml 很明显是 `/a` 这个URI 重复定义了，换个其他路径即可

谢谢老哥。不懂就问，老哥是怎么看出来的啊？我看这个报错没有提到这个url重复呀
