### ISSUE TITLE
Is there any plan to implement SSH sessions in CrossC2?

### ISSUE THREAD

**Issue by HellooTiger** [gloxec/CrossC2#108]
Is there any plan to implement SSH sessions in CrossC2? Just like the windows beacons, https://www.cobaltstrike.com/help-ssh. That's could enrich the capability of lateral move in Linux/Unix environment for crossc2 beacons. Currently,  the ssh command cannot use in beacons generated by CrossC2.

**Comment by gloxec** [comment]
Yes, this part is already under development.

But unlike the official, it is not implemented natively with ssh. Instead, use the CrossC2Kit plug-in to update. The bottom layer will pass the CrossC2 beacon/bind-beacon to the host through sshpass to move laterally.

The operation method is similar to that of the native client. Select the host list through the Target interface, specify the session and listener, fill in the account password, and automatically implant the beacon/bind-beacon, and finally establish a connection with the teamserver.

**Comment by gloxec** [comment]
Yes, this part is already under development.

But unlike the official, it is not implemented natively with ssh. Instead, use the CrossC2Kit plug-in to update. The bottom layer will pass the CrossC2 beacon/bind-beacon to the host through sshpass to move laterally.

The operation method is similar to that of the native client. Select the host list through the Target interface, specify the session and listener, fill in the account password, and automatically implant the beacon/bind-beacon, and finally establish a connection with the teamserver.

**Comment by gloxec** [comment]
Some functions of the beacon end have been basically realized.
After the long-term bug fixes started in v2.2.x, the development of new functions of beacon has basically ended.
From now on, the v3.x version will be pushed, and it will focus on the implementation of process injection and other functions around the newly launched libbeacon.

Now the team can stably perform functions such as process injection under Linux 64-bit (through the process list UI interface), but other platforms such as Linux 32 and MacOS have not yet been implemented.

Now the remaining multi-part functions will be implemented through the `cna` plug-in (with **CrossC2Kit**), so I also hope that interested people can directly submit the code to the CrossC2Kit directory.
Workflow will be launched later to release the stable and usable `cna` plugin for CrossC2 beacon.

**Comment by HellooTiger** [comment]
> From now on, the v3.x version will be pushed, and it will focus on the implementation of process injection and other functions around the newly launched libbeacon.

That's a nice idea. Focusing on some particular functions that are hard to be implemented  is imperative, such as process injection.

CrossC2Kit idea is also great. That's pretty much a plugin system, like IDA pro. It is not surprise to see how versatile  IDA pro shall be  with the development of the plugin system.

**Comment by HellooTiger** [comment]
The other question. What does the CrossC2 can do right now with respect to the lateral movement? There is not any doc on this subject, but a checklist mark.

**Comment by gloxec** [comment]
Use `Linux-bind` & `Mac-bind` to manage hosts in the intranet. The most stable function for managing child nodes so far is still the `shell` command. However, at this stage, manual horizontal distribution of bindbeacon is still required.

target2: ./Linux-bind 4455
target1 cs session: connect \<target2-ip\> 4455
new target2 cs session: shell whoami

https://github.com/gloxec/CrossC2/blob/cs4.1/README_full.md#lateral-movement
![img](https://raw.githubusercontent.com/gloxec/CrossC2/cs4.1/media/15901534124389/15985513904454.jpg)
