### ISSUE TITLE
生成的木马不上线，可以帮忙看看嘛

### ISSUE THREAD

**Issue by chenchenhen6** [gloxec/CrossC2#109]
插件我按照修改了CrossC2.cna的路径，将genCrossC2.MacOS和.cobaltstrike.beacon_keys放在同一个路径，配置了https监听，生成的木马的流程没有任何报错
![image](https://user-images.githubusercontent.com/35289748/130206064-ba33f3a1-039e-47ee-9265-da72e1074f6e.png)
执行不上线
我又按照本地生成的方式生成木马执行也不上线
![image](https://user-images.githubusercontent.com/35289748/130206716-866758c3-6abb-4e62-a997-0e2b501db376.png)
![image](https://user-images.githubusercontent.com/35289748/130207151-1d22f881-6f6a-4f86-a4b9-14c8d8bceb74.png)
没有报错，但就是不上线，实在是不知道是哪里出了问题，求大佬指导

**Comment by gloxec** [comment]
1. 查看WebLog界面，以及teamserver输出信息
2. export CCDEBUG=1后再去执行beacon试试？

**Comment by ddm-alt** [comment]
> 1. 查看WebLog界面，以及teamserver输出信息
> 2. export CCDEBUG=1以后再去执行beacon实用？
 
你好，我的也是相同问题，CS版本是4.3，上线了ubuntu之后，日志报错   Dropped HTTP client from /192.168.88.117 (missing URI)
请问这个如何处理呢？

**Comment by chenchenhen6** [comment]
![image](https://user-images.githubusercontent.com/35289748/130316409-a08107d9-1682-4d45-8f42-bf62552b174a.png)
我的weblog后台总是输入这样的信息，是不是因为我启动的时候启动了C2文件导致不上线

**Comment by gloxec** [comment]
@hanchen666 你的teamserver在启动时配置了c2profile吧？或者说cs是否是三方patch过的版本？

关于teamserver配置c2profile后需要指定对应的c2profile，具体参照: https://github.com/gloxec/CrossC2/blob/cs4.1/README_zh.md#usage

**Comment by gloxec** [comment]
> 你好，我的也是相同问题，CS版本是4.3，上线了ubuntu之后，日志报错 Dropped HTTP client from /192.168.88.117 (missing URI)

@ddm-alt teamserver启动是否有配置c2profile？以及CrossC2版本，是否尝试过v2.2.4, v2.2.2版本？

**Comment by gloxec** [comment]
@ddm-alt 试试这个[版本](https://github.com/gloxec/CrossC2/releases/download/v2.2.5/genCrossC2.Linux-2021-08-27)可以上线吗？

**Comment by mooneee** [comment]
我也出现了同样的问题，我试过不加载profile也是无法上线，一直弹出 Dropped HTTP client from /222.*.*.118 (missing URI)，请问是怎么回事儿？ 我改过证书，用的是CrossC2 3.0.2  cs4.3

**Comment by gloxec** [comment]
@mooneee 有详细报错信息吗
