### ISSUE TITLE
Sleep did not work

### ISSUE THREAD

**Issue by trickster0** [gloxec/CrossC2#11]
Hello  i was testing this against linux and i typed sleep 5 but the listener kept going up to 1 min .
Also i executed shell commands or pwd and they didn't work. my system was the latest kali.

**Comment by gloxec** [comment]
Try cs 3.14 version?

**Comment by trickster0** [comment]
that is the one i tried. also i could not create the binary from cobalt strike. i had to create it manually. not sure why. I did change the line in the .cna to the path of genCross.Linux.
Not sure why it doesn't work. maybe i am doing something wrong?

**Comment by gloxec** [comment]
Version 3.14 is confirmed to run normally. Cna does not work. Maybe it's a problem with the exec path? The exec function of the cs Aggressor script does not seem to support special symbols.

**Comment by trickster0** [comment]
exec("/home/three/cobaltstrik3.14/genCrossC2.Linux"." ".$host." ". $port." null null ".$system." ".$arch." ".$outputFileName)

looks fine no?

**Comment by trickster0** [comment]
![Untitled](https://user-images.githubusercontent.com/20028117/75732326-db5b6200-5cfa-11ea-84bc-d827fe9f8578.png)
Okay i fixed the issue for creating the binary but the commands won't work i guess...

**Comment by gloxec** [comment]
you using version 3.14?

**Comment by trickster0** [comment]
yup

**Comment by gloxec** [comment]
<img width="999" alt="image" src="https://user-images.githubusercontent.com/5158011/75732914-ca2c4880-5d2e-11ea-8e5d-0cfa04747065.png">
My test is normal.

**Comment by trickster0** [comment]
I really do not know what the issue is. I ran strace on the beacon and it seems like it tries to grab the command but I guess it doesn't? :/

**Comment by trickster0** [comment]
I tried it on a new Kali, same thing... i am using reverse_https beacon listener right?

**Comment by gloxec** [comment]
According to the situation, it should be that the past data sent by the beacon is not correctly parsed. This situation will only be related to the cs version and has nothing to do with the target system.

**Comment by trickster0** [comment]
![Untitled](https://user-images.githubusercontent.com/20028117/75756998-39f40080-5d3a-11ea-9583-0babe24ea1c2.png)
 
:/

**Comment by gloxec** [comment]
<img width="529" alt="image" src="https://user-images.githubusercontent.com/5158011/75762573-dedfff00-5d75-11ea-9972-a56b3eff7d53.png">
Please use the latest bug fixes version.

**Comment by trickster0** [comment]
that was indeed the issue :)
