### ISSUE TITLE
mac下生成载荷失败

### ISSUE THREAD

**Issue by Nixiabing** [gloxec/CrossC2#114]
启动后直接被killed
![image](https://user-images.githubusercontent.com/20591728/130547792-805e54ce-8f0a-4fe8-a33d-a136e126ccde.png)

![image](https://user-images.githubusercontent.com/20591728/130547829-f3e6c3b7-04fe-4ff7-ab85-4ff56a8955ad.png)

**Comment by Nixiabing** [comment]
2.2.5不行
2.2.4可以

![image](https://user-images.githubusercontent.com/20591728/130548214-96eb33fa-0847-41b4-b1a7-7a165c84fdba.png)

**Comment by gloxec** [comment]
在"控制台.app"中查看下是否有进程崩溃报告？
