### ISSUE TITLE
cannot generate Stagless file

### ISSUE THREAD

**Issue by P-T001** [gloxec/CrossC2#115]
CobaltStrike 4.1.8

CrossC2 v2.2.5

# uname -a  # centos 7
Linux racknerd-ae060e 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

# java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

执行./genCrossC2.Linux时出现错误信息：
*[error] :      error platform
*[error] :      cannot generate Stagless file

**Comment by gloxec** [comment]
系统平台选择错误了吧？
./genCrossC2 ... Linux x64 ...

**Comment by P-T001** [comment]
是我选错了 。
但是生成成功后上线不了，我试了
centos6 32位 （Linux localhost.localdomain 2.6.32-131.0.15.el6.i686 #1 SMP Sat Nov 12 17:30:50 CST 2011 i686 i686 i386 GNU/Linux）有进程，但是没上线成功
和直接在cs服务器上centos7 （Linux racknerd-ae060e 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux）运行没有进程

**Comment by gloxec** [comment]
export CCDEBUG=1 && /tmp/c2 输出结果是什么呢？
以及cs weblog输出信息
teamserver输出信息

**Comment by P-T001** [comment]
我是用./genCrossC2.linux ... Linux x86 ...  直接生成的文件，这个/tmp/c2应该是改成我的生成马的路径是吧？
运行之后没有回显
cs weblog 输出信息："GET /load" 404 0 ""
teamserver输出信息的日志里面最后一行是我创建监听器的日志。。

**Comment by P-T001** [comment]
而且我用windows客户端来加载插件时，遇到这样的问题：
![微信图片_20210902110353](https://user-images.githubusercontent.com/35355973/131775278-b5ad36fb-54de-4c06-8605-c5be48c4ee98.png)

文件内容是这样：
![微信截图_20210902110433](https://user-images.githubusercontent.com/35355973/131775280-25450945-db4d-408a-ba69-7eef52d1b8a0.png)

**Comment by gloxec** [comment]
> cs weblog 输出信息："GET /load" 404 0 ""

teamserver启动时配置了c2profile吧？或者说cs是patch过的非原版？

配置过c2profile的话详见 https://github.com/gloxec/CrossC2/blob/cs4.1/README_zh.md#usage 第四项`生成beacon`说明

**Comment by gloxec** [comment]
> 而且我用windows客户端来加载插件时，遇到这样的问题：
> ![微信图片_20210902110353](https://user-images.githubusercontent.com/35355973/131775278-b5ad36fb-54de-4c06-8605-c5be48c4ee98.png)

直接加载也出现同样的报错吗？因为这里文件丢失了换行符，所以无法定位到具体是哪行的语法错误了，大概率是符号前后没有闭合导致。
建议使用非notepad的专业编辑器去修改配置

**Comment by P-T001** [comment]
1.teamserver启动使用的是默认的呀。没有用c2profile。。
2.原本不修改是可以加载的，我用notepad++去修改也不行。。

**Comment by gloxec** [comment]
> 1.teamserver启动使用的是默认的呀。没有用c2profile。。

"GET /load" 404 该行为是beacon成功与teamserver建立连接，但teamserver所采用的profile未配置`/load`URI导致。
官方发布的cs4.x默认版本是使用`/load`, 后期有无更新未做测试。可以贴一份你cs解压后,`resources/default.profile`内容吗？

> 2.原本不修改是可以加载的，我用notepad++去修改也不行。。

那说明文件本身语法没有问题，大概率是你CC2_PATH中修改携带的路径符号导致前后无法闭合

**Comment by P-T001** [comment]
1.cobaltstrike.store.profile里面没有/load，可能是我这款别人修改了： set uri "/owa/";
2.我重新复制一个cna通过notepad++去修改后可以加载，可能是因为之前那个cna文件被notepad修改过不行

**Comment by gloxec** [comment]
> 1.cobaltstrike.store.profile里面没有/load，可能是我这款别人修改了： set uri "/owa/";

要么配c2profile，然后根据文档去配置crossc2的rebind.so
要么使用官方原版，或者是copy官方原本的default.profile中http-get & http-post内容再添加一份字段，在创建listener时选定即可

**Comment by P-T001** [comment]
我换了cs4.1版本，用windows的客户端的插件去生成马链接让靶机上线，但是还是不能上线
这个版本c2profile应该是默认的，没看到有profile文件
监听器的日志：
[root@racknerd-ae060e cobaltstrike4.1]# vi logs/210903/weblog_55413.log 
[09/03 03:50:51 UTC] "GET /a" 200 226 "page Script Unix Web Delivery (curl)" "O"
[09/03 03:50:52 UTC] "GET /spfCMbEyNc" 200 1851484 "page CrossC2 beacon Linux x64" "O"

**Comment by gloxec** [comment]
teamserver有无输出信息呢？是否使用该版本呢？
https://github.com/gloxec/CrossC2/releases/download/v2.2.5/genCrossC2.Win-2021-09-01.zip

**Comment by P-T001** [comment]
teamserver 没有输出相关信息，使用的是CrossC2 v2.2.4版本
我想知道，使用插件生成马时，arch选项是客户端系统(即生成马的系统)的架构还是靶机系统的架构？还有这个马能对32位的linux系统靶机上线吗？还是说只能64位？

**Comment by gloxec** [comment]
arch是靶机架构，支持32 & 64
其中-platform,-arch都是指靶机
建议使用: https://github.com/gloxec/CrossC2/releases/download/v2.2.5/genCrossC2.Win-2021-09-01.zip
或使用: https://github.com/gloxec/CrossC2/releases/download/v3.0/genCrossC2.Linux

**Comment by P-T001** [comment]
我用了你说的文件，
windows客户端用插件生成命令进行上线，上线不了，还是一样的效果。。

cs服务器（centos7）用./genCrossC2.Linux 【IP】 【https监听器端口】 null null Linux x86 test2，生成的马丢给靶机运行之后，使用ps -ef没看到这个马文件在运行。。

我还有一点疑惑，genCrossC2.Linux命令x86这个位置选项是指靶机还是指生成马的系统的架构，我用x64会生成错误，x86才生成成功（cs服务器是x86架构）。。按照你的说法，这个架构选项应该对应着arch，靶机架构才对呀。。

**Comment by gloxec** [comment]
> ./genCrossC2.Linux 【IP】【https监听器端口】 null null Linux x86 test2，靶机运行之后，使用ps -ef没看到在运行

`strace -ff -o res.txt ./c2 ` 运行后贴下两份报告结果

> 我还有一点疑惑，genCrossC2.Linux命令x86这个位置选项是指靶机还是指生成马的系统的架构，我用x64会生成错误

arch这个是靶机架构，genCrossC2客户端本身只有64位，所以不存在架构选择问题。麻烦贴下错误信息

**Comment by P-T001** [comment]
运行： strace -ff -o res.txt ./c2 
```
execve("./test2", ["./test2"], 0x7ffcb8425078 /* 25 vars */) = 0
open("/proc/self/exe", O_RDONLY)        = 3
mmap(NULL, 971052, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xf76b0000
mmap(0xf76b0000, 970830, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0) = 0xf76b0000
mprotect(0xf779c000, 4396, PROT_READ|PROT_EXEC) = 0
readlink("/proc/self/exe", "/root/ceshi/test2", 4055) = 17
mmap2(0x8048000, 2932736, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x8048000
mmap2(0x8048000, 6635, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x8048000
mprotect(0x8048000, 6632, PROT_READ)    = 0
mmap2(0x804a000, 2604419, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x804a000
mprotect(0x804a000, 2604416, PROT_READ|PROT_EXEC) = 0
mmap2(0x82c6000, 255027, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x82c6000
mprotect(0x82c6000, 255024, PROT_READ)  = 0
mmap2(0x8305000, 45675, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x8305000
mprotect(0x8305000, 45672, PROT_READ|PROT_WRITE) = 0
mmap2(0x8311000, 9144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x8311000
brk(0x8314000)                          = 0x9a31000
open("/lib/ld-linux.so.2", O_RDONLY)    = -1 ENOENT (没有那个文件或目录)
exit(127)                               = ?
+++ exited with 127 +++
```
之前会报该错误，但是现在我用了新的genCrossC2.Linux之后用x64又不会报错了，正常生成
*[error] : error platform
*[error] : cannot generate Stagless file

**Comment by gloxec** [comment]
> 运行： strace -ff -o res.txt ./c2
> 
> ```
> execve("./test2", ["./test2"], 0x7ffcb8425078 /* 25 vars */) = 0
> open("/proc/self/exe", O_RDONLY)        = 3
> ...
> open("/lib/ld-linux.so.2", O_RDONLY)    = -1 ENOENT (没有那个文件或目录)
> exit(127)                               = ?
> +++ exited with 127 +++
> ```

搜索了/lib/ld-linux.so.2找不到的问题，似乎是因为在64位系统运行了32位程序的原因？
https://stackoverflow.com/questions/14030306/lib-ld-linux-so-2-bad-elf-interpreter-no-such-file-or-directory
麻烦贴写下上述错误的`c2`运行环境:
1. ` uname -a`
2. ` ldd --version`

> 之前会报该错误，但是现在我用了新的genCrossC2.Linux之后用x64又不会报错了，正常生成
> *[error] : error platform
> *[error] : cannot generate Stagless file

该错误仅是判断 `-platform` 是否为`Linux/MacOS/Linux-bind/MacOS-bind`, `-arch`是否为`x86/x64`。
单纯的大小写敏感字符串对比，若不对就会输出上述信息并直接退出。

**Comment by gloxec** [comment]
> centos6 32位 （Linux localhost.localdomain 2.6.32-131.0.15.el6.i686 #1 SMP Sat Nov 12 17:30:50 CST 2011 i686 i686 i386 GNU/Linux）有进程，但是没上线成功
> 和直接在cs服务器上centos7 （Linux racknerd-ae060e 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux）运行没有进程

> （cs服务器是x86架构）

突然发现根据你两次贴文，系统架构写混乱了吧？
根据第一次的贴文,你的cs服务器应该是centos 7 x64，靶机是centos6 x86

**Comment by P-T001** [comment]
**centos7 靶机c2运行环境**
[root@localhost ~]# uname   ##-a
Linux localhost.localdomain 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost ~]# ldd --version
ldd (GNU libc) 2.17
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
由 Roland McGrath 和 Ulrich Drepper 编写。

第一次贴文使用的是centos6  32位 ，然后我以为是系统或者位数问题，就换成centos7 x86 64位

**Comment by gloxec** [comment]
> [root@localhost ~]# ldd --version
> ldd (GNU libc) 2.17

glibc 2.17 确认是支持的，CrossC2支持 >= glibc2.3的系统

> cs服务器（centos7）用./genCrossC2.Linux 【IP】 【https监听器端口】 null null Linux x86 test2

这里生成的beacon为32位

> **centos7 靶机c2运行环境**
> [root@localhost ~]# uname ##-a
> Linux localhost.localdomain 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

centos7是64位，应当使用 ./genCrossC2.Linux 【IP】 【https监听器端口】 cs_key null Linux x64 test2


> > 运行： strace -ff -o res.txt ./c2
> > ```
> > execve("./test2", ["./test2"], 0x7ffcb8425078 /* 25 vars */) = 0
> > open("/proc/self/exe", O_RDONLY)        = 3
> > ...
> > open("/lib/ld-linux.so.2", O_RDONLY)    = -1 ENOENT (没有那个文件或目录)
> > exit(127)                               = ?
> > +++ exited with 127 +++
> > ```
> 
> 搜索了/lib/ld-linux.so.2找不到的问题，似乎是因为在64位系统运行了32位程序的原因？
> https://stackoverflow.com/questions/14030306/lib-ld-linux-so-2-bad-elf-interpreter-no-such-file-or-directory

所以之前的问题可以确认是因为在64位系统centos7上，在未安装32位兼容环境的情况下，运行32位beacon程序导致的报错

**Comment by P-T001** [comment]
x64 x86不是架构么?

**Comment by P-T001** [comment]
我用了./genCrossC2.Linux 【IP】 【https监听器端口】 cs_key null Linux x64 test2 ，还是没有上线

 strace -ff -o res.txt ./c2
```
uname({sysname="Linux", nodename="localhost.localdomain", ...}) = 0
getuid()                                = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
connect(3, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (没有那个文件或目录)
close(3)                                = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
connect(3, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (没有那个文件或目录)
close(3)                                = 0
open("/etc/nsswitch.conf", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=1717, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faf4ef12000
read(3, "#\n# /etc/nsswitch.conf\n#\n# An ex"..., 4096) = 1717
read(3, "", 4096)                       = 0
close(3)                                = 0
munmap(0x7faf4ef12000, 4096)            = 0
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=21047, ...}) = 0
mmap(NULL, 21047, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7faf4ef0d000
close(3)                                = 0
open("/lib64/libnss_files.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260!\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=61560, ...}) = 0
mmap(NULL, 2173048, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7faf4d779000
mprotect(0x7faf4d785000, 2093056, PROT_NONE) = 0
mmap(0x7faf4d984000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xb000) = 0x7faf4d984000
mmap(0x7faf4d986000, 22648, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7faf4d986000
close(3)                                = 0
mprotect(0x7faf4d984000, 4096, PROT_READ) = 0
munmap(0x7faf4ef0d000, 21047)           = 0
open("/etc/passwd", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=1040, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7faf4ef12000
read(3, "root:x:0:0:root:/root:/bin/bash\n"..., 4096) = 1040
close(3)                                = 0
munmap(0x7faf4ef12000, 4096)            = 0
stat("/etc/sysconfig/64bit_strstr_via_64bit_strstr_sse2_unaligned", 0x7ffdb0b3bdb0) = -1 ENOENT (没有那个文件或目录)
open("/dev/urandom", O_RDONLY|O_NOCTTY|O_NONBLOCK) = 3
fstat(3, {st_mode=S_IFCHR|0666, st_rdev=makedev(1, 9), ...}) = 0
poll([{fd=3, events=POLLIN}], 1, 10)    = 1 ([{fd=3, revents=POLLIN}])
read(3, "\231mp9|v\361?\363\rd\326\302\244\247\301\224\355\2413\211\202\353\200o\260E\334\262\221\323\326", 32) = 32
close(3)                                = 0
getuid()                                = 0
socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 3
connect(3, {sa_family=AF_INET, sin_port=htons(4444), sin_addr=inet_addr("192.168.1.2")}, 16) = -1 ECONNREFUSED (拒绝连接)
stat("/etc/resolv.conf", {st_mode=S_IFREG|0644, st_size=73, ...}) = 0
socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 4
connect(4, {sa_family=AF_INET, sin_port=htons(4444), sin_addr=inet_addr("192.168.1.2")}, 16) = -1 ECONNREFUSED (拒绝连接)
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigaction(SIGCHLD, NULL, {sa_handler=SIG_IGN, sa_mask=[CHLD], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7faf4deda400}, 8) = 0
nanosleep({tv_sec=60, tv_nsec=0}
```
防火墙我是关了的，难道我的cs规则不是默认的? - -！

**Comment by gloxec** [comment]
这里的分类与所有系统定义分类一致
x64指64位系统
x86指各类ix86系列的32位系统 (i386、i486、i586、i686等等)

**Comment by gloxec** [comment]
这里新的tracelog已经是成功运行采集信息与c2尝试进行连接了

```
socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 3
connect(3, {sa_family=AF_INET, sin_port=htons(4444), sin_addr=inet_addr("192.168.1.2")}, 16) = -1 ECONNREFUSED (拒绝连接)
stat("/etc/resolv.conf", {st_mode=S_IFREG|0644, st_size=73, ...}) = 0
socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 4
connect(4, {sa_family=AF_INET, sin_port=htons(4444), sin_addr=inet_addr("192.168.1.2")}, 16) = -1 ECONNREFUSED (拒绝连接)
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigaction(SIGCHLD, NULL, {sa_handler=SIG_IGN, sa_mask=[CHLD], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7faf4deda400}, 8) = 0
nanosleep({tv_sec=60, tv_nsec=0}
```

但这里提示拒绝连接，应该是系统或其他本地的网络策略，与beacon本身无关。
