### ISSUE TITLE
CS4.1 linux上线不能执行命令

### ISSUE THREAD

**Issue by Freeverthing** [gloxec/CrossC2#116]
linux上线了，但是文件系统和命令执行都失败，脚本管理器也加载kit

**Comment by gloxec** [comment]
使用的CrossC2版本，以及是否有截图？
参考issue是否是类似的原因:

cs 4.0版本命令执行无回显 #51
cs 4.1无法执行命令 #43
为什么使用cs4.1能上线但是无法执行命令呢？ #38

**Comment by Freeverthing** [comment]
使用的版本为cs4.0的crossc2,cobalstrike也是4.0，具体的问题就如图中这样，上线成功，文件系统ui排序和命令执行失败。

从 Windows 版邮件发送

发件人: hooooooooooook
发送时间: 2021年9月4日 13:48
收件人: gloxec/CrossC2
抄送: Freeverthing; Author
主题: Re: [gloxec/CrossC2] CS4.1 linux上线不能执行命令 (#116)

使用的CrossC2版本，以及是否有截图？
参考issue是否是类似的原因:
cs 4.0版本命令执行无回显 #51
cs 4.1无法执行命令 #43
为什么使用cs4.1能上线但是无法执行命令呢？ #38
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gloxec** [comment]
未看到截图，不过根据描述，你的情况与该问题极为相似:
使用cs4.0 GUI生成的不能上线，使用的4.0分支 https://github.com/gloxec/CrossC2/issues/41#issuecomment-728736076
cs 4.0版本命令执行无回显 https://github.com/gloxec/CrossC2/issues/51#issuecomment-749968011

上线不能执行命令的问题是因为cs各个版本之间采用的协议有区别，所以无法通用。
大致分类cs3.14, cs4.0, cs4.x(>=4.1)三种协议，cs4.0 2019版本测试可正常使用(cs4.0 2020版未做测试)。
https://verify.cobaltstrike.com

项目主页有介绍各个分支以及release页面对应的cs版本说明，你的cs4.0版本是从这里下载的吗？https://github.com/gloxec/CrossC2/blob/cs4.0/src/genCrossC2.Win.exe


建议使用cs4.1或更高版本，4.0对应的CrossC2已经很久不更新了。

**Comment by Freeverthing** [comment]
4.1的分支src目录下没有windows的exe gen，那我该使用哪个版本的gencrossc2呢？发送自我的盖乐世
-------- 原始信息 --------发件人： hooooooooooook ***@***.***> 日期: 2021/9/4  13:48  (GMT+08:00) 收件人： gloxec/CrossC2 ***@***.***> 抄送： Freeverthing ***@***.***>, Author ***@***.***> 主题： Re: [gloxec/CrossC2] CS4.1 linux上线不能执行命令 (#116) 

使用的CrossC2版本，以及是否有截图？

参考issue是否是类似的原因:

cs 4.0版本命令执行无回显 #51

cs 4.1无法执行命令 #43

为什么使用cs4.1能上线但是无法执行命令呢？ #38

**Comment by gloxec** [comment]
4.1分支的都在release页面中发布，主页的Readme有详细介绍
