### ISSUE TITLE
cs4.1下创建载荷失败 3.0.1 dev

### ISSUE THREAD

**Issue by array0111** [gloxec/CrossC2#120]
师傅您好，打扰一下。晚上试用了一下3.0.1 dev 发现有closef函数的地方有报错，我把没有openf读取的过程中的closef删除就可以正常运行了，师傅有时间麻烦看看。

**Comment by array0111** [comment]
与#104问题相同

**Comment by gloxec** [comment]
按理说这里并不影响后续的执行，因为这里是为了判断是否为unix系统，cna在win下是正常工作的
后续将用原生系统判断函数，替换此处的uname方案

**Comment by array0111** [comment]
好的感谢师傅，我测试用的是mac环境，但win环境貌似也有问题，我明天尝试了再回复师傅。
