### ISSUE TITLE
cs4.1生成linux 64位无法在Ubuntu arm架构系统运行

### ISSUE THREAD

**Issue by linuxdy** [gloxec/CrossC2#121]
1.Ubuntu架构信息

/bin/bash: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=67d150eb0f362d8a6ef60714f1f45dd654fe2234, for GNU/Linux 3.7.0, stripped

![image](https://user-images.githubusercontent.com/50064309/135714439-cedd1462-aa16-4d74-b6fb-5d0e2880f870.png)

2.c2生成

![image](https://user-images.githubusercontent.com/50064309/135714580-fca51287-bb68-4467-9757-2cd5f1ea9fa5.png)

3.上线报错

-bash: ./test999111: cannot execute binary file: Exec format error

![image](https://user-images.githubusercontent.com/50064309/135714516-292ad311-d8d0-4fb4-9ea9-8593d33acfde.png)

**Comment by gloxec** [comment]
Linux暂不支持arm架构，后期考虑加入arm & mips架构
