### ISSUE TITLE
cs4.4加载rebind.so后执行报错

### ISSUE THREAD

**Issue by Emptytao** [gloxec/CrossC2#125]
cs版本：4.4
cs.profile:
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/26384334/139876245-decf34aa-972a-4779-92af-e04bbce39272.png">
rebind.c:
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/26384334/139876491-66d6b2ba-8a49-4e33-8d0c-c6a485a94f3c.png">
错误：
<img width="756" alt="image" src="https://user-images.githubusercontent.com/26384334/139876765-84398abb-3ed9-4747-8792-e2de25b14780.png">

**Comment by gloxec** [comment]
genCrossC2是在什么环境下使用的呢？

**Comment by Emptytao** [comment]
> genCrossC2是在什么环境下使用的呢？

mac系统，利用插件生成
<img width="670" alt="image" src="https://user-images.githubusercontent.com/26384334/140014832-b365c9a8-9ac9-4def-a90f-cc9a7ebbb884.png">

**Comment by gloxec** [comment]
很抱歉在清除issue时才看到后续回复，根据报错提示`invalid ELF header`显示，应当是rebind.c编译生成的动态库rebind.so存在问题，按描述需要在Linux低版本下编译后才可正常使用
