### ISSUE TITLE
VPS存在内网IP的情况下无法上线

### ISSUE THREAD

**Issue by NHPT** [gloxec/CrossC2#126]
按步骤配置好并生成Payload后，在目标主机执行时发生错误：
![1](https://user-images.githubusercontent.com/42366434/140258744-34a5df89-9209-46d7-81bb-a6e1418bdae9.png)
定位错误发现C2使用了内网IP未使用外网IP：
![2](https://user-images.githubusercontent.com/42366434/140258800-cb1ab50c-8c65-445c-bee5-c5579a0b052e.png)

**Comment by gloxec** [comment]
使用的CrossC2.cna是从哪个版本中获取的呢？

**Comment by gloxec** [comment]
测试发现该问题应该是你在创建`windows/beacon_https/reverse_https`时未正确设定HOST，所以创建CrossC2 Listener时从原生的 reverse_https 中继承了错误的HOST值，最终在写入Script时写入错误的内网IP
