### ISSUE TITLE
CS 4.4 第二阶段payload无法生成

### ISSUE THREAD

**Issue by taomujian** [gloxec/CrossC2#128]
第二阶段payload内容为空,c为windos,s为debian

**Comment by taomujian** [comment]
root@vm:~/CS4.4# ./genCrossC2.Linux XXXX 8443 /root/CS4.4/.cobaltstrike.beacon_keys null Linux x64 /root/CS4.4/t_cc2.out stageless 4.4


         ▄████▄   ██▀███   ▒█████    ██████   ██████     ▄████▄   ██████▄
        ▒██▀ ▀█  ▓██ ▒ ██▒▒██▒  ██▒▒██    ▒ ▒██    ▒    ▒██▀ ▀█        ██░
        ▒▓█    ▄ ▓██ ░▄█ ▒▒██░  ██▒░ ▓██▄   ░ ▓██▄      ▒▓█        █████▒
        ▒▓▓▄ ▄██▒▒██▀▀█▄  ▒██   ██░  ▒   ██▒  ▒   ██▒   ▒▓▓▄ ▄█ ░▒██
        ▒ ▓███▀ ░░██▓ ▒██▒░ ████▓▒░▒██████▒▒▒██████▒▒   ▒ ▓███▀  ░▒▓█████▓
        ░ ░▒ ▒  ░░ ▒▓ ░▒▓░░ ▒░▒░▒░ ▒ ▒▓▒ ▒ ░▒ ▒▓▒ ▒ ░   ░ ░▒ ▒    ░▒ ░▓ ░░
          ░  ▒     ░▒ ░ ▒░  ░ ▒ ▒░ ░ ░▒  ░ ░░ ░▒  ░ ░     ░  ▒     ░ ░░ ░
        ░          ░░   ░ ░ ░ ░ ▒  ░  ░  ░  CrossC2 v3.0.2 # dev @hook
        ░ ░         ░         ░ ░        ░        ░     ░ ░          ░
        ░                                               ░

{cs = 4.1 ~ 4.4}
read keys error!
generate beacon keys error
*[error] : read key error

**Comment by taomujian** [comment]
.cobaltstrike.beacon_keys文件是在cs根目录的

**Comment by taomujian** [comment]
在服务端手动生成也不行，类似的issue已看过，没用

**Comment by AdiEcho** [comment]
一开始我也和你报一样的错，后来成功解决，在这里记录一下看看你能不能一样解决这个问题

1. 在服务器端删除cobaltstrike.store和.cobaltstrike.beacon_keys
2. 生成证书，用teamserver第46行的参数
3. 重新运行teamsever
4. 复制新生成的cobaltstrike.store和.cobaltstrike.beacon_keys回客户端
5. 生成payload

希望对你有帮助

**Comment by taomujian** [comment]
我试了下，还是不行

**Comment by Tcotl** [comment]
同样的文件 师傅解决了吗？

**Comment by Tcotl** [comment]
同样的问题 师傅解决了吗？

**Comment by Tcotl** [comment]
> 
> 
> 一开始我也和你报一样的错，后来成功解决，在这里记录一下看看你能不能一样解决这个问题
> 
>     1. 在服务器端删除cobaltstrike.store和.cobaltstrike.beacon_keys
> 
>     2. 生成证书，用teamserver第46行的参数
> 
>     3. 重新运行teamsever
> 
>     4. 复制新生成的cobaltstrike.store和.cobaltstrike.beacon_keys回客户端
> 
>     5. 生成payload
> 
> 
> 希望对你有帮助

试过了还是不行

**Comment by gloxec** [comment]
@taomujian @Tcotl 

尝试使用这样?

```
./genCrossC2.Linux XXXX 8443 /root/CS4.4/.cobaltstrike.beacon_keys null Linux x64 /root/CS4.4/t_cc2.out stageless 4.3

或

./genCrossC2.Linux XXXX 8443 /root/CS4.4/.cobaltstrike.beacon_keys null Linux x64 /root/CS4.4/t_cc2.out
```

该问题出现在cs4.4的`.cobaltstrike.beacon_keys`解析上
现目前解决后发现目前大家使用的4.4版本有两种:

一种解析 **beacon_key** 使用4.4更新过的方法：

```
./genCrossC2.Linux XXXX 8443 /root/CS4.4/.cobaltstrike.beacon_keys null Linux x64 /root/CS4.4/t_cc2.out stageless 4.4
```

一种似乎只是将旧版cs4.3中组件替换进了4.4的jar包中，所以会导致生成时：`read keys error!`
所以这里应该使用：

```
./genCrossC2.Linux XXXX 8443 /root/CS4.4/.cobaltstrike.beacon_keys null Linux x64 /root/CS4.4/t_cc2.out stageless 4.3
```

**Comment by taomujian** [comment]
可以了，感谢感谢

**Comment by Tcotl** [comment]
![图片](https://user-images.githubusercontent.com/88639567/142821252-3dc426b6-ab0d-47d5-933d-c67f1efada80.png)

之前是key的错误 把key重置以后出现这个文件
CS4.4的版本 腾讯云的VPS 在服务器本地生成payload。
不知道是什么问题影响的，系统刚刚重置的。

**Comment by Tcotl** [comment]
解决了，感谢！
