### ISSUE TITLE
cs 4.3 linux_tcp 上线主机不稳定

### ISSUE THREAD

**Issue by SnowMeteors** [gloxec/CrossC2#129]
使用cs4.3 crossc2为最新版
先生成一个linux tcp bind 监听3333端口
![image](https://user-images.githubusercontent.com/47601098/141405150-9c626c04-e85a-45cf-bdb7-650670d1c72e.png)
上传木马到靶机，connect 192.168.93.120 3333，正向连接立马上线
![image](https://user-images.githubusercontent.com/47601098/141407893-514a2469-08d3-48cf-a039-09c766212026.png)
过一分钟过后，自动掉线，无法执行任何命令
![image](https://user-images.githubusercontent.com/47601098/141408009-86df18b3-7528-4595-9411-3fc48b2fd9f1.png)
![image](https://user-images.githubusercontent.com/47601098/141408079-08dfda56-0d9b-4455-94be-4da8f4b1a581.png)
请问是什么情况

**Comment by gloxec** [comment]
尝试使用该格式连接呢？

```
connect ip:port
```

**Comment by SnowMeteors** [comment]
> 尝试使用该格式连接呢？
> 
> ```
> connect ip:port
> ```

无法解决
