### ISSUE TITLE
内网横向移动的MacOS-bind.beacon和Linux-bind.beacon在哪里下载

### ISSUE THREAD

**Issue by zi0n8** [gloxec/CrossC2#136]
生成 Linux-bind / MacOS-bind 类型的beacon
内网中的目标运行 ./MacOS-bind.beacon <port> 开启服务
在网络联通的session中运行 connect <targetIP>:<port>

运行的文件有下载链接吗？谢谢

**Comment by gloxec** [comment]
genCrossC2以及GUI菜单中都可生成，指定生成类型为 `Linux-bind / MacOS-bind ` 即可
