### ISSUE TITLE
cs4.3：配合malleablec2后linux能上线，mac无法上线

### ISSUE THREAD

**Issue by XingYun-Cloud** [gloxec/CrossC2#137]
profile
![image](https://user-images.githubusercontent.com/43715449/147546653-1dab16eb-d898-4525-bad4-ac18c3bd9fb3.png)
自定义协议（使用的`https://github.com/gloxec/CrossC2/issues/89#issuecomment-861194022`最后的自定义协议）
![image](https://user-images.githubusercontent.com/43715449/147546402-f49b3c05-84dc-487d-9a9d-f2f9a2b71b96.png)
weblog图忘了截了，现在清掉了，但是Linux可以正常上线，MacOS不行，因为请求的路径一直是`/load`而不是自定义协议里的`/jquery-3.3.1.min.js`

**Comment by gloxec** [comment]
可否贴下CrossC2以及MacOS版本？

**Comment by gloxec** [comment]
新版对MacOS做了兼容处理，请重新尝试
https://github.com/gloxec/CrossC2/releases/tag/v3.1.0
