### ISSUE TITLE
Linux可以上线 MacOS无法上线 报错Invalid Address: [0xffffe301]

### ISSUE THREAD

**Issue by solradmin** [gloxec/CrossC2#145]
![image](https://user-images.githubusercontent.com/96558941/154482817-98c8419f-713c-46e6-94a6-35dad02ac7be.png)

![image](https://user-images.githubusercontent.com/96558941/154482891-ed2395d4-96ea-486e-a9ab-5121e0d13294.png)

**Comment by gloxec** [comment]
是Intel还是M1芯片呢？

**Comment by solradmin** [comment]
> 

使用intel i7 cpu 物理机搭建的Vmware 虚拟macos big sur 测试环境

**Comment by gloxec** [comment]
@solradmin 新版 **v3.1.0** 针对 MacOS做了兼容处理，请重新尝试
https://github.com/gloxec/CrossC2/releases/tag/v3.1.0

**Comment by xnianq** [comment]
> 
MACOS
CrossC2版本: v3.1.0
系统版本：
<img width="473" alt="image" src="https://user-images.githubusercontent.com/17513849/172522369-936d09f9-d1e2-4b62-a003-8bbc6b87539d.png">
使用自定义profile，上线时，发现出现以下问题，so库是在当前机器下编译的。

请大佬帮忙看下～
[error]: [parse lib]: dlopen(./.sys.rrcache.data, 0x0001): tried: './.sys.rrcache.data' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/xxxx/tools/CS4.4/.sys.rrcache.data' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))!
<img width="582" alt="image" src="https://user-images.githubusercontent.com/17513849/172522689-40f72874-d96d-41c4-922d-5ed5df0f442d.png">

**Comment by gloxec** [comment]
@xnianq 尝试编译动态库时，指定生成架构为x86_64

**Comment by xnianq** [comment]
@gloxec 已解决， 感谢
