### ISSUE TITLE
shell whoami 无回显

### ISSUE THREAD

**Issue by Pd1r** [gloxec/CrossC2#15]
Linux centos-7.shared 3.10.0-862.11.6.el7.x86_64  
能touch文件
sleep 0 需要多次才能顺利设置成功
shell whoami 无回显
可以帮忙看一下嘛 ,多谢啦🙏
![image](https://user-images.githubusercontent.com/30740738/78640263-07fa2f00-78e2-11ea-8f83-5d0a03d8f8eb.png)

**Comment by gloxec** [comment]
请使用cs3.14 bug fixes版本，参考issue #11

**Comment by Pd1r** [comment]
👌
