### ISSUE TITLE
cs4.4生成会后多了一个lib文件

### ISSUE THREAD

**Issue by websecer** [gloxec/CrossC2#150]
cs4.4版本，生成server后，另外还有一个server.lib ./server运行后可以上线，但是会提示unresolved

**Comment by gloxec** [comment]
生成的server.lib为beacon动态库，方便进行其他方式的植入
提示的unresolved是beacon尝试使用 `gethostbyname` 去解析域名，失败后的错误提示，该问题大多在于dns解析失败的环境，例如nslookup相同请求无结果

**Comment by websecer** [comment]
感谢，学到了。
