### ISSUE TITLE
成功生成后内网机器运行后无法上线，VPS 上运行秒上线

### ISSUE THREAD

**Issue by a646465071** [gloxec/CrossC2#151]

**Comment by gloxec** [comment]
是使用了域名上线的方式吗？发现仅指定域名上线的方式在部分平台上存在问题，暂时请使用指定IP的方式，将在下一版中进行修复

**Comment by gloxec** [comment]
@a646465071 新版 **v3.1.0** 已修复该问题
https://github.com/gloxec/CrossC2/releases/tag/v3.1.0
