### ISSUE TITLE
cs4.4文件管理问题

### ISSUE THREAD

**Issue by websecer** [gloxec/CrossC2#152]
我用的4.4加载了loader，然后我在cs右键explore->文件管理，输入/打开根目录，然后双击tmp目录，就会变成了/\tmp\，当然打开的目录也无法显示文件，显示空

**Comment by gloxec** [comment]
遇到这种情况建议手动重新输入目录进入
`/\tmp\`
这里的第一个`\`字符是第一次打开`/`时，cs客户端自动添加的后缀，
第二个`\`字符同上，出现两次的原因大概率是cs还未收到teamserver返回结果，提前变更目录，导致后续第二次请求目录时，cs向teamserver提交了错误的路径

这里出现`\`后缀的原因是cs本身为Windows设计，每次请求新目录时会向用户指定的路径后添加`\`符号，保证目录正确。
所以unix上为了保证目录不出错，beacon会强制修正结尾的`\`，但像上面提到的情况，手动重新输入目录后再次请求一次即可。

以及上述问题导致的另外一个问题需要手动点击左侧目录树去主动刷新右侧数据
