### ISSUE TITLE
设置sleep时间

### ISSUE THREAD

**Issue by riijj** [gloxec/CrossC2#155]
经观察，beacon的sleep时间应该是3-4s，这个在实际的情况中可能存在较频繁的情况，建议提供相应的功能或提供rebind接口来设置sleep时间。

**Comment by gloxec** [comment]
默认的sleep时间确实是这样，可以在上线后
1. 手动使用sleep 60s功能去更改时间
2. 利用cna插件去自动修改
```javascript
on ssh_initial {
    bsleep($1, 60);
}
```

感谢通过rebind接口设置的建议，现已实现通过类似c2profile配置去设置内部的一些默认变量，例如这里的sleep时间，以及其他的pipe名称等。
以及在rebind处添加了 **init阶段** 以及 **网络连接错误的reConnect阶段** 的hook功能，方便用户做自定义的信息搜集后的静默策略
上述功能将会在近期整理完API文档后进行推送

**Comment by wgf4242** [comment]
`on ssh_initial ` 加在哪个文件？
我加在 CrossC2Kit_Loader.cna 末尾没有效果。

**Comment by wgf4242** [comment]
`on ssh_initial `这段加在哪里，我加到 `CrossC2Kit_Loader.cna`没有效果。
