### ISSUE TITLE
4.4 版本 自动退出程序

### ISSUE THREAD

**Issue by orleven** [gloxec/CrossC2#156]
mac linux 运行的时候， 在listen 前加一个nginx，然后c2上线。
如果cs返回超时，导致nginx返回502，这时候 crossc2会报错终止程序。

下面是strace 情况：
17:16:37.826976 --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x14} ---
17:16:37.828011 +++ killed by SIGSEGV +++

**Comment by gloxec** [comment]
有无使用过c2profile呢？

**Comment by orleven** [comment]
> 有无使用过c2profile呢？

已经解决了，用的是实例里的c2profile，里面c2profile.c的函数strstr(rawData, start) 会有异常，前面加个null判断就好了
