### ISSUE TITLE
cs4.4无法生成stager

### ISSUE THREAD

**Issue by st-lucifer** [gloxec/CrossC2#157]
123是生成的文件，生成4.4就会报错
![image](https://user-images.githubusercontent.com/17016792/163201463-a9da2a95-45e1-4a5b-a2c0-c72e964f0be7.png)
![image](https://user-images.githubusercontent.com/17016792/163201503-1370ff56-5a3d-440e-a493-5382903486d5.png)
![image](https://user-images.githubusercontent.com/17016792/163201536-1c578f94-68ae-48c0-8021-1ff37a269f41.png)

**Comment by gloxec** [comment]
试试使用4.3去生成呢?
cs4.4 外网流传的大致有两个版本，一个是源码版本的，一个是打包后的
源码版本的需要在生成时指定4.4
打包版本的需要在生成时指定4.3
