### ISSUE TITLE
生成payload错误

### ISSUE THREAD

**Issue by sharp-shooter** [gloxec/CrossC2#16]
$ ./genCrossC2.Linux 127.0.0.1 4444 null null Linux x64 ./CrossC2-test

 ▄████▄   ██▀███   ▒█████    ██████   ██████     ▄████▄   ██████▄ 
▒██▀ ▀█  ▓██ ▒ ██▒▒██▒  ██▒▒██    ▒ ▒██    ▒    ▒██▀ ▀█        ██░
▒▓█    ▄ ▓██ ░▄█ ▒▒██░  ██▒░ ▓██▄   ░ ▓██▄      ▒▓█        █████▒ 
▒▓▓▄ ▄██▒▒██▀▀█▄  ▒██   ██░  ▒   ██▒  ▒   ██▒   ▒▓▓▄ ▄█ ░▒██      
▒ ▓███▀ ░░██▓ ▒██▒░ ████▓▒░▒██████▒▒▒██████▒▒   ▒ ▓███▀  ░▒▓█████▓
░ ░▒ ▒  ░░ ▒▓ ░▒▓░░ ▒░▒░▒░ ▒ ▒▓▒ ▒ ░▒ ▒▓▒ ▒ ░   ░ ░▒ ▒    ░▒ ░▓ ░░
  ░  ▒     ░▒ ░ ▒░  ░ ▒ ▒░ ░ ░▒  ░ ░░ ░▒  ░ ░     ░  ▒     ░ ░░ ░ 
░          ░░   ░ ░ ░ ░ ▒  ░  ░  ░  ░  ░  ░     ░         by:░hook
░ ░         ░         ░ ░        ░        ░     ░ ░          ░    
░                                               ░                 

Exception in thread "main" java.lang.NoClassDefFoundError: common/CommonUtils
	at genKey.BeaconKey.main(BeaconKey.java:52)
Caused by: java.lang.ClassNotFoundException: common.CommonUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 1 more
*[error] : read key error

请问这个是怎么回事呢 我已经把.cobaltstrike.beacon_keys拷贝到相应目录下了，还是报这个错误

ll
total 9396
drwxrwxr-x  3 yang yang    4096 4月   8 11:44 ./
drwxr-xr-x 44 yang yang    4096 1月  19 09:22 ../
-rwxrw-rw-  1 yang yang    1447 4月   8 11:33 .cobaltstrike.beacon_keys*
-rwxrw-rw-  1 yang yang 9603876 4月   7 20:05 genCrossC2.Linux*

**Comment by gloxec** [comment]
genCrossC2放至cs根目录下, 详情参照wiki, issue #1

**Comment by sharp-shooter** [comment]
复制了，还是一样的错误

**Comment by gloxec** [comment]
看错误就是无法正确读取到cobaltstrike.jar文件导致的，需要放同目录，且保证原jar包正常

**Comment by sharp-shooter** [comment]
您好，上个问题解决了，是我的cobaltstrike.jar名字不对，然后在Linux上边运行刚生成的payload，在web log里边一直提示404，如下所示：
04/10 18:51:41 visit from: 
	Request: GET /load
	Response: 404 Not Found
	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko)  Chrome52.0.2743.116 Safari/537.36

请问这是怎么回事呢 ，提前谢谢了

**Comment by gloxec** [comment]
你是不是用的自定义的c2profile？
crossc2目前的版本只支持默认的profile, 不过已经在写了，后面会推送:p

**Comment by 1522402210** [comment]
@gloxec 
[14:22:59] invalid use of index operator: $null['host'] at CrossC2.cna:34

提示这个错

**Comment by 1522402210** [comment]
另外，我看 CrossC2.cna 的源码，有两个 null 
    $process = exec("/xxx/xx/xx/genCrossC2"." ".$host." ". $port." null null ".$system." ".$arch." ".$outputFileName);
    @data = readAll($process);
    closef($process);

我放好的文件位置：
![image](https://user-images.githubusercontent.com/25600994/79305200-84fe5780-7f25-11ea-9a34-2155e070ad10.png)

**Comment by 1522402210** [comment]
Mac Pro 
./genCrossC2.Linux 10.2.0.5 1000 null null linux x86 /tmp/CrossC2-test 
zsh: exec format error: ./genCrossC2.Linux

报错

**Comment by gloxec** [comment]
你用MacOS的话，需要使用genCrossC2.MacOS可执行文件，$process = exec("/xxx/xx/xx/genCrossC2.MacOS" . ".$host." ".

**Comment by gloxec** [comment]
> @gloxec
> [14:22:59] invalid use of index operator: $null['host'] at CrossC2.cna:34
> [14:26:04] null value error at CrossC2.cna:39
> 
> 提示这个错

这个你需要检查下listener是否创建错误或者选择错误?

**Comment by 1522402210** [comment]
@gloxec 好的，我用的是4.0 。可能是版本问题？ 
你可以在readme 加个支持版本 ^_^
