### ISSUE TITLE
通过域名上线时心跳极慢

### ISSUE THREAD

**Issue by pastcloud** [gloxec/CrossC2#161]
如题，能用有响应，profile设置心跳在5s，但实际心跳大约在两分钟左右，也无法手动修改sleep时间

**Comment by gloxec** [comment]
是否使用了c2profile呢？可能出现的原因有对应通讯库中的HTTP头编写存在问题
```c
Connection: close 正确
Connection: keep-alive 可能会导致心跳时间过长
```

**Comment by pastcloud** [comment]
十分感谢，检查了一下我的profile确实设置了keep-alive，修改后就正常了

**Comment by hosch3n** [comment]
遇到了相同的问题，之前以为是bug现在已解决，感谢

**Comment by jiakun02** [comment]
我设置的是close但是心跳会在一定的次数后中断，是为什么?，我的CS版本是4.9.1,genCrossC2是最新版
