### ISSUE TITLE
cs4.4版本在windows平台下使用genCrossC2生成的beacon异常

### ISSUE THREAD

**Issue by Margular** [gloxec/CrossC2#169]
等待作者修复

**Comment by Margular** [comment]
等待作者修复，我顶！

**Comment by gloxec** [comment]
该问题发现是 `genCrossC2.exe` 在生成指定 `rebind_dynamic_lib` 协议库的路径为绝对路径时，将解析失败。相对路径则不受影响。

```
genCrossC2.exe ... c:\toos\so\rebind.so    ...   [error]
genCrossC2.exe ... toos\so\rebind.so:config.ini    ...   [ok]
genCrossC2.exe ... .\so\rebind.so    ...   [ok]      
```

该问题将导致**GUI插件**在自动生成beacon时，选定`rebind_dynmaic_lib`后因为转换为绝对路径的问题，最终生成失败。
所以可以手动将 `插件输入框中的绝对路径` 或 `命令行的rebind参数`  改为相对路径。

或着更新 [genCrossC2.Win生成器](https://github.com/gloxec/CrossC2/releases/download/v3.1.0/genCrossC2.Win-2022-07-13-bug-fix.zip)
