### ISSUE TITLE
ServerScan 等插件中文结果输出乱码

### ISSUE THREAD

**Issue by Adminisme** [gloxec/CrossC2#17]
内存加载和调用 ServerScan 等插件，输出中文结果输出乱码，且输出内容已经强制指定为UTF-8编码。
Please更正环境变量。

**Comment by gloxec** [comment]
thx，已修复,  release v1.1
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/5158011/79043679-36a23d80-7c33-11ea-89eb-97dfab600df2.png">
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/5158011/79043699-50438500-7c33-11ea-8f1e-e9594ccb9dc2.png">
