### ISSUE TITLE
支持cs4.5

### ISSUE THREAD

**Issue by riijj** [gloxec/CrossC2#170]
cs4.5已经公开了，建议增加对cs4.5的支持，官方解密的key: f38eb3d1a335b252b58bc2acde81b542 , 
 
推荐一个一劳永逸方法, 可以考虑在输入版本的选项上新增手动输入解密密钥，如果是输入的4.4这样的版本号调用内部内置的密钥，如果版本号输入的是key，直接使用key

**Comment by gloxec** [comment]
默认是 **cs4.x** 都支持的，单独列 cs4.4 是因为当初有两个版本
1. 传统的cobaltstrike.jar (cs4.x 支持, 生成时默认参数，或指定`4.1`、`4.2`、`4.3`等都是兼容的)
2. 官方发布的源码版本 (不兼容，专门做了个特殊适配，生成beacon时需要指定 `4.4-src` )

可以先本地测试下 cs4.5 是否可以正常使用

**Comment by riijj** [comment]
经测试，确实支持cs4.5，感谢师傅
