### ISSUE TITLE
CS4.0，win10上线报错

### ISSUE THREAD

**Issue by bingling123** [gloxec/CrossC2#171]
![image](https://user-images.githubusercontent.com/48980951/174243593-f2091e02-c3d6-4e1d-9e75-78e0ca154e90.png)
如图
木马是直接在命令行生成的：
![image](https://user-images.githubusercontent.com/48980951/174243710-6cc05da4-4716-401d-8025-7fa9eaf3f0f1.png)

命令行上线也报错：
![image](https://user-images.githubusercontent.com/48980951/174244137-1b2aa749-d46d-41ab-beaf-16295f227953.png)
![image](https://user-images.githubusercontent.com/48980951/174244207-71ab64a6-ae43-4b43-9dfc-b700dd3e3530.png)

**Comment by gloxec** [comment]
1. teamserver是否配置了 c2profile?

2. 根据截图，命令行上线错误是第一阶段的beacon未成功部署，在event界面查看是否有成功生成 & 部署的信息
```
05/01 23:31:03 *** /mnt/cc2/genCrossC2.MacOS 172.16.251.1 5555 /tmp/beacon_keys null MacOS x64 /tmp/CrossC2-test
05/01 23:31:06 *** genCrossC2 beacon -> *[success] :    Packed 1532232 byte.   成功生成
05/01 23:31:07 *** xxxx hosted CrossC2 beacon MacOS x64 @ http://172.16.251.1:55413/iqEBVKwHoZ  成功部署beacon
```

**Comment by bingling123** [comment]
teamserver未配置c2profile
部署是成功了的
![image](https://user-images.githubusercontent.com/48980951/174251229-aab85ece-9868-4978-b478-b237fabbf3b5.png)
下面是服务端报错：
![image](https://user-images.githubusercontent.com/48980951/174251412-f690050e-dee9-4971-a2e7-7b6bd6d8d4a9.png)

**Comment by gloxec** [comment]
1. 查看下 view-> web log 信息
2. Attacks->Web Drive-by->Manage 中查看是否已经配置过 /a 的URL，导致产生了资源冲突

**Comment by gloxec** [comment]
突然发现你使用的cs4.0
4.0 需要去分支中专门下载 https://github.com/gloxec/CrossC2/tree/cs4.0/src

建议使用4.1及以上CobaltStrike, 4.0版本已两年多未更新，上线后使用中可能遇到一些bug
