### ISSUE TITLE
CrossC2 for CS4.0 /bin/sh shell无法执行命令

### ISSUE THREAD

**Issue by ltfafei** [gloxec/CrossC2#173]
/bin/bash可以正常回显：
![image](https://user-images.githubusercontent.com/43526141/174420904-5a27126d-1ab5-427f-95f1-e2988d9f1be5.png)

/bin/sh无法回显：
![image](https://user-images.githubusercontent.com/43526141/174420925-f24a975a-a1ea-479b-93c0-ce5ff9863035.png)

**Comment by gloxec** [comment]
> /bin/sh无法回显： 
![image](https://user-images.githubusercontent.com/43526141/174420925-f24a975a-a1ea-479b-93c0-ce5ff9863035.png)

可以看到这里其实同样回显了结果`command not found`，可能是环境变量的问题导致`sh`无法找到`ls`程序
建议`shell export `查看环境变量，接着使用`setenv`功能添加目录后再进行尝试 
```
ex:
shell export     /     shell echo $PATH

setenv PATH /usr/bin/:/usr/sbin/:/bin/:/sbin/
```

**Comment by ltfafei** [comment]
感谢师傅指点，果然是环境变量的问题哎
