### ISSUE TITLE
配置了cloudflare上线不了

### ISSUE THREAD

**Issue by r00t7oo2jm** [gloxec/CrossC2#178]
请问下，配置了cloudflare，是不是还需要配置rebind库，怎么配置呢？

**Comment by gloxec** [comment]
需要按照c2profile配置对应的rebind库，具体参考[主页写的文档介绍](https://github.com/gloxec/CrossC2/blob/cs4.1/README_zh.md)和[代码例子](https://github.com/gloxec/CrossC2/tree/cs4.1/protocol_demo)
