### ISSUE TITLE
最新版的genCrossC2.Linux不支持生成32位的payload

### ISSUE THREAD

**Issue by ltfafei** [gloxec/CrossC2#181]
![image](https://user-images.githubusercontent.com/43526141/189540663-7226bd3f-2239-47b5-a1ff-a70b04c0ec40.png)

**Comment by gloxec** [comment]
运行平台和命令是什么呢？这边Linux下测试是OK的

**Comment by ltfafei** [comment]
> 

运行平台64位Ubuntu

**Comment by gloxec** [comment]
生成命令是什么呢？还有genCrossC2最新已经到3.1.0版本了，图中我看使用的是旧版2.0

**Comment by ltfafei** [comment]
好吧，支持4.5，不支持4.4，可以了。
![image](https://user-images.githubusercontent.com/43526141/189654230-5690310c-7991-47d0-84c8-c47b3e29412a.png)

**Comment by ltfafei** [comment]
可以正常上线，真棒！

**Comment by gloxec** [comment]
cs4.4 也是支持的

cs4.4 当初流传了两个版本，一个是正常发布的，一个是源码打包的
正常发布的默认是直接支持的，源码打包的需要特殊指定参数

图中出现的 "keys error" 错误，可以在指定版本后解决
```
./genCrossC2 127.0.0.1 4444 null null Linux x64 ./a.out stager 4.4-src
```

**Comment by ltfafei** [comment]
> cs4.4 也是支持的
> 
> cs4.4 当初流传了两个版本，一个是正常发布的，一个是源码打包的 正常发布的默认是直接支持的，源码打包的需要特殊指定参数
> 
> 图中出现的 "keys error" 错误，可以在指定版本后解决
> 
> ```
> ./genCrossC2 127.0.0.1 4444 null null Linux x64 ./a.out stager 4.4-src
> ```

好的
