### ISSUE TITLE
mac m1有办法使用genCrossC2.Macos生成payload吗

### ISSUE THREAD

**Issue by NaliangzzZ** [gloxec/CrossC2#182]
mac m1有办法使用genCrossC2.Macos生成payload吗

**Comment by gloxec** [comment]
1. xattr -c genCrossC2.Macos后尝试运行

2. 部分 m1 测试运行是正常的，可以说下失败时，系统的基础信息吗？
cpu: m1 ? m1x?
os: Monterey 10.1.1 ?
`$ csrutil status` 运行结果

**Comment by NaliangzzZ** [comment]
SIP开着，os：Ventura，cpu：m1 pro，是指令集的问题

**Comment by NaliangzzZ** [comment]
`# xattr -c genCrossC2.Macos`
`# ./genCrossC2.Macos`
`zsh: segmentation fault  ./genCrossC2.MacOS`

**Comment by gloxec** [comment]
@NaliangzzZ 最新版已解决，同类问题见: https://github.com/gloxec/CrossC2/issues/190
