### ISSUE TITLE
win7下无法使用

### ISSUE THREAD

**Issue by W01fh4cker** [gloxec/CrossC2#185]
cc2是最新版的，cs是4.3的，作者大大如果觉得没必要的话就可以直接关闭此issue QAQ
![image](https://user-images.githubusercontent.com/101872898/208835036-6c1e9389-e606-4bd2-a978-d634b936a0f4.png)

**Comment by gloxec** [comment]
cc2是使用x64编译的，不清楚是不是因为你所使用环境为win7 32位，暂无win7更新计划，建议其他环境生成

**Comment by W01fh4cker** [comment]
收到
