### ISSUE TITLE
为什么加载很多插件，但就是显示不了？怎么使用这些插件尼？

### ISSUE THREAD

**Issue by qiuluo-oss** [gloxec/CrossC2#186]
![image](https://user-images.githubusercontent.com/72497146/209761959-57b2ed0c-f2f1-4702-900c-083fca47a6fd.png)

**Comment by gloxec** [comment]
`CrossC2Kit_demo`这个仅是用于插件编写的样例

自带的插件仅需加载 `CrossC2Kit_Loader.cna` , 在GUI界面可以看到部分功能的菜单，以及在会话界面中输入 `help` 也可得到插件的功能描述
