### ISSUE TITLE
Gather - Dump Password  - Linux 64没有反应，要怎么查找问题？

### ISSUE THREAD

**Issue by wgf4242** [gloxec/CrossC2#187]
teamserver,client,weblog窗口都看了。
什么信息都没。

**Comment by gloxec** [comment]
可能是低版本Linux的问题，
https://github.com/CrossC2/CrossC2Kit/commit/4e828ee498c16a1799f014cd6518f4b0e74efbdc 中已修复，但release页面中还未自动化合并

需要手动下载https://github.com/CrossC2/CrossC2Kit 进行更新
