### ISSUE TITLE
macOS Ventura更新后报错segmentation fault (inter)

### ISSUE THREAD

**Issue by thelostworldFree** [gloxec/CrossC2#190]
➜  Desktop ./genCrossC2.MacOS
[1]    57928 segmentation fault  ./genCrossC2.MacOS
<img width="532" alt="image" src="https://user-images.githubusercontent.com/24971604/218273804-7d623690-0a90-4785-8949-2f9e743f27b6.png">

**Comment by gloxec** [comment]
手边无Ventura系统进行测试，暂时先使用Linux进行代替吧，后续会找环境测试该问题

**Comment by thelostworldFree** [comment]
好的 谢谢

**Comment by x-Ai** [comment]
> ➜ Desktop ./genCrossC2.MacOS [1] 57928 segmentation fault ./genCrossC2.MacOS <img alt="image" width="532" src="https://user-images.githubusercontent.com/24971604/218273804-7d623690-0a90-4785-8949-2f9e743f27b6.png">

是UPX壳导致的问题

**Comment by K4ptor** [comment]
> > ➜ 桌面 ./genCrossC2.MacOS [1] 57928 分段错误 ./genCrossC2.MacOS<img alt="图像" width="532" src="https://user-images.githubusercontent.com/24971604/218273804-7d623690-0a90-4785-8949-2f9e743f27b6.png">
> 
> 是UPX外壳致的问题

这个目前有办法解决吗？

**Comment by K4ptor** [comment]
> 手边无Ventura系统进入测试，暂时先使用Linux进入替代吧，后续会找环境测试该问题

用Linux生成的mac马运行也报错

**Comment by x-Ai** [comment]
> > 手边无Ventura系统进入测试，暂时先使用Linux进入替代吧，后续会找环境测试该问题
> 
> 用Linux生成的mac马运行也报错

目前最新的UPX 4.02压缩后在Ventura上也不正常，UPX项目里有类似的issues。

**Comment by gloxec** [comment]
> 目前最新的UPX 4.02压缩后在Ventura上也不正常，UPX项目里有类似的issues。

@thelostworldFree @x-Ai  @sincere9  可尝试对`genCrossC2`生成器使用 ups -d 进行解压后再使用，若可解决问题的话，后续将beacon将支持原始非压缩的生成方式。

**Comment by OFalwl** [comment]
> > 目前最新的UPX 4.02压缩后在Ventura上也不正常，UPX项目里有类似的issues。
> 
> @thelostworldFree @x-Ai @sincere9 可尝试对`genCrossC2`生成器使用 ups -d 进行解压后再使用，若可解决问题的话，后续将beacon将支持原始非压缩的生成方式。

能不能genCrossC2-Linux生成的时候加个参数，不要加UPX的壳生成的。然后自己去做免杀。生成出来的服务端，直接用upx -d解压不了还，还要手动脱UPX。麻烦作者搞个生成原生服务端的参数不加壳的。谢谢了

**Comment by gloxec** [comment]
@OFalwl 感谢建议👍，下个版本采用该方案来生成

**Comment by gloxec** [comment]
@OFalwl 最新版已支持upx可选压缩 https://github.com/gloxec/CrossC2/releases/tag/v3.2

**Comment by OFalwl** [comment]
> @OFalwl 最新版已支持upx可选压缩 https://github.com/gloxec/CrossC2/releases/tag/v3.2

非常感谢。

**Comment by 5yqht6** [comment]
> @OFalwl 最新版已支持upx可选压缩 https://github.com/gloxec/CrossC2/releases/tag/v3.2
请问下，这个upx可选参数怎么加，有格式吗？

**Comment by dead5nd** [comment]
下载的最新版本，inter mac13.4.1 ，还是会爆一样的错误，cs客户端显示生成了但是文件里面啥都没有，各位师傅有一样情况的吗？

**Comment by gloxec** [comment]
@dead5nd 生成器在Ventura上会因为upx的问题导致无法运行，建议brew install upx后，upx -d genCrossC2.Mac进行解压后再去使用
