### ISSUE TITLE
Dropped HTTP client from /*.*.*.* (missing URI)

### ISSUE THREAD

**Issue by aqgaw** [gloxec/CrossC2#191]
您好，linux上线碰到这种情况，请问怎么解决
![image](https://user-images.githubusercontent.com/95491386/218559143-44cf1f64-9f0b-4e80-8fbd-3aacd4a37690.png)
![image](https://user-images.githubusercontent.com/95491386/218560005-17805b58-c3d3-49af-a2d5-000a7ede1ff3.png)
![image](https://user-images.githubusercontent.com/95491386/218560159-47215989-466f-4ba7-a158-8df61a78f260.png)

**Comment by gloxec** [comment]
应该是listener的问题，应该使用 https 而非 http

**Comment by aqgaw** [comment]
谢谢，可以了
