### ISSUE TITLE
cs的crossc2插件用于linux环境在使用cloudflare cdn环境下各种尝试均无法上线的问题

### ISSUE THREAD

**Issue by tdtc7** [gloxec/CrossC2#197]
<html>
<body>

第一次完全按照教程通过gui创建监听及web投递脚本后续在本地虚拟机的kali环境、teamserver 的vps、靶机三种linux环境下发现文件均可通过curl访问cnd域名走web投递顺利落地，但均无法上线，应该可以排除防火墙端口原因，kali环境下我的防火墙相关服务都是关闭的。感觉可能是默认生成的监听器配置有点怪，遂第二次尝试编辑监听器配置，并在teamserver的linux命令行环境下自行生成指向crossc2监听器的反连后门直接传输命令行生成的后门到上述三种环境里多次执行，发现同样无法完成上线遂第三次尝试直接在teamserver上bash命令行生成指向cs自己默认的windows/becaon_https/reverse_https监听器，同样在三种linux环境下单独手动wget下载并本地多次执行依旧无法上线……到这里小弟已经技穷了，只得来坛里问问各位表哥有没有什么解决姿势，或者是我还坑没踩完处于一个身在坑里不自知的状态，看了下之前的各种文章是不是根本原因是crossc2现如今还无法支持这么搞？如果是那么有没有什么替代方案？linux后渗透下隐藏流量特征c2地址这些的姿势（frp只实现得了代理不能当后门暂不考虑）环境和cloudflare、c2.profile等等各项配置基本是按照坛里这位表哥的姿势来的https://www.t00ls.com/viewthread.php?tid=64900

另外是不是最近cloudflare的对于境内的稳定性又变差了最近在windows测试靶机环境下选择不同时段多次反复执行指向cloudflare cdn地址的cs马，感觉平均30多次才能成功上线一次的样子，失败率奇高……

</body>
</html>

**Comment by gloxec** [comment]
CrossC2对cf的CDN是稳定支持的，但需要配置正确的流量模板，有两种方式可完成:
1. 早期版本可参考自定义流量编写对应rebind.c
2. 后期dev版本可自解析c2profile，无需编写rebind.c，所有流量按c2profile中的配置进行发包，为了CDN可正确解析，c2profile中在http-get/post中要配置正确的Host头

```
http-get {
    set uri "/xxxxx";
    set verb "GET";
    client {
	header "Host" "www.example.com";  <------------ 配置正确解析域名
        ...
    }
}

http-post {
    set uri "/xxxx";
    set verb "POST";
    client {
	header "Host" "www.example.com";
        ...
    }
}
```
