### ISSUE TITLE
Execution stop after parse ";;c2.profile" with no beacon generation

### ISSUE THREAD

**Issue by hdbreaker** [gloxec/CrossC2#199]
Hi, I'm trying to generate a beacon using the new CLI command added in versión 3.1.1:

`./genCrossC2.Linux ip port ./cobaltstrike.beacon_keys ";;c2.profile" Linux x64 ./beacon`

Result:
<img width="842" alt="Screen Shot 2023-07-28 at 05 08 04" src="https://github.com/gloxec/CrossC2/assets/5799585/8bf05a7b-0fc7-4ac2-9115-85bac38f78b4">

Expected result: Beacon generation

https.profile from demo folder was used in the test.

**Comment by gloxec** [comment]
I didn't reproduce the same problem.
Try to use the previous **stable** version and use the default generation method to see if you can get beacon?
`genCrossC2.Linux 127.0.0.1 443 *cskey* null Linux x64 ./beacon`
