### ISSUE TITLE
发现好慢，并且执行命令都失败了，有遇到的没？

### ISSUE THREAD

**Issue by yaoxiaodai** [gloxec/CrossC2#20]

**Comment by gloxec** [comment]
慢是因为采用cs默认的60s睡眠机制，可以用sleep指令去指定睡眠时间。
执行命令失败是指？没有返回结果？还是？
如果是单纯的没有返回结果，很大概率是版本问题，建议使用cs3.14最后一个bug fixes版本。
如果是server收到报错，应该是key没有更新所导致。
如果weblog中提示404，则是profile问题，暂不支持自定义c2profile（自定义流量协议已完成，将很快在下个版本推出）。

**Comment by coolbabay** [comment]
大佬牛逼 生成的可执行文件好像不是所有linux平台都兼容 红帽试了下can not execute binary file ,用msf生成的elf可以执行

> 慢是因为采用cs默认的60s睡眠机制，可以用sleep指令去指定睡眠时间。
> 执行命令失败是指？没有返回结果？还是？
> 
> 1. 如果是单纯的没有返回结果，很大概率是版本问题，建议使用cs3.14最后一个bug fixes版本。
> 2. 如果是server收到报错，应该是key没有更新所导致。
> 3. 如果weblog中提示404，则是profile问题，暂不支持自定义c2profile（自定义流量协议已完成，将很快在下个版本推出）。

**Comment by yaoxiaodai** [comment]
> 慢是因为采用cs默认的60s睡眠机制，可以用sleep指令去指定睡眠时间。
> 执行命令失败是指？没有返回结果？还是？
> 
> 1. 如果是单纯的没有返回结果，很大概率是版本问题，建议使用cs3.14最后一个bug fixes版本。
> 2. 如果是server收到报错，应该是key没有更新所导致。
> 3. 如果weblog中提示404，则是profile问题，暂不支持自定义c2profile（自定义流量协议已完成，将很快在下个版本推出）。

师傅好，我直接运行底层程序生成的运行文件，在kali下执行，成功收到了回连。但是执行任何命令都无回显，卡死，获取的beacon 无pid
![image](https://user-images.githubusercontent.com/28942595/79713430-5c4cd800-8300-11ea-988f-552623a20258.png)

**Comment by gloxec** [comment]
> 大佬牛逼 生成的可执行文件好像不是所有linux平台都兼容 红帽试了下can not execute binary file ,用msf生成的elf可以执行
> 

这个报错似乎是架构的问题，可否方便发下`uname -a`结果

**Comment by gloxec** [comment]
> 师傅好，我直接运行底层程序生成的运行文件，在kali下执行，成功收到了回连。但是执行任何命令都无回显，卡死，获取的beacon 无pid
> ![image](https://user-images.githubusercontent.com/28942595/79713430-5c4cd800-8300-11ea-988f-552623a20258.png)

确定是3.14 bug fixs版本吗，你的状况与 issue #11  很相似
