### ISSUE TITLE
How long to support 4.5??

### ISSUE THREAD

**Issue by jciason** [gloxec/CrossC2#200]
How long to support 4.5??

{cs = 4.1 ~ 4.4}
rebind lib: null
[./.cobaltstrike.beacon_keys] : read keys error
generate beacon keys error
*[error] : read key error

**Comment by gloxec** [comment]
support 4.x (4.0-4.8)

The reasons for reading beacon keys errors may be:
1. The specified beacon keys file path is wrong
2. An unofficial version is used, and beacon keys related modifications have been made internally

https://verify.cobaltstrike.com/
