### ISSUE TITLE
主机上线后，一周左右不登录客户端，在登录的时候会掉鸡

### ISSUE THREAD

**Issue by websecer** [gloxec/CrossC2#202]
主机上线后，一周左右不登录客户端，在登录的时候会掉鸡，我经常用这个插件上线linux，这个问题怎么导致的我不清楚，就是一周左右在连接到服务器，发现掉了一些机器

**Comment by websecer** [comment]
有人说过这个插件的bug，需要自己调试通讯库才行，不确定是不是这个问题

**Comment by gloxec** [comment]
可以详细版本信息吗？正常应该是很稳定的，这边有测试稳定使用N月无掉线情况

1. CS版本
2. CrossC2版本
3. CrossC2生成信息: 默认流量 / 动态库 / 指定c2profile自动解析？
4. teamserver & beacon之间通讯架构：beacon直连 / 域名解析 / CDN / nginx ?
5. teamserver & beacon之间通讯：中间有无teamserver离线等
6. 登陆时掉线是指：登陆后发现已掉线很久 / 登陆成功时才异常掉线？

**Comment by websecer** [comment]
我之前用的，发现不稳定后我就删除了，具体版本也没记住，最近在用，但是cs换了4.8，请问支持4.8吗，我目前为成功上线linux机器

**Comment by gloxec** [comment]
4.8支持，如果还出现类似的问题需详细贴下上面的问题

**Comment by websecer** [comment]
好的
