### ISSUE TITLE
cs 自定义profile

### ISSUE THREAD

**Issue by coolbabay** [gloxec/CrossC2#21]
好像是不支持自定义的profile cs，使用自定义的ssl 证书不上

**Comment by gloxec** [comment]
是的，readme中有注明c2profile暂时还不支持，不过自定义协议流量相关功能已经实现，将在下个版本推出。

**Comment by gloxec** [comment]
新功能已可实现，参考release v1.3 & [wiki - 通信协议API](https://gloxec.github.io/CrossC2/zh_cn/protocol/)
