### ISSUE TITLE
It doesn't work on MacOS Sonoma

### ISSUE THREAD

**Issue by raghavmishra** [gloxec/CrossC2#213]
The documentation says, we need to modify CrossC2.cna but the there is no file with such name. There is filename "CrossC2-GithubBot-2023-11-20.cna" which asks to add the path of CC2 even changing that not getting the connect back from MacOS.

**Comment by raghavmishra** [comment]
Looks like not compatible with latest version of Cobaltstrike.

**Comment by gloxec** [comment]
> "CrossC2-GithubBot-2023-11-20.cna" 

CrossC2-GithubBot-2023-11-20.cna == CrossC2.cna

> Looks like not compatible with latest version of Cobaltstrike.

Judging from feedback from other issues, the latest version(4.9.1) is still supported.

Maybe you are running on MacOS, so you need to pay attention to whether `cobaltstrike` itself is allowed access to the directory where `genCrossC2` is located. This is the security policy of the macos system itself.

After `CrossC2.cna` is configured normally, when `beacon` is generated, the `cli` running command for debugging will be output in the terminal of `CobaltStrike`. If there is an error, you can copy it to the terminal and run the test manually.

**Comment by raghavmishra** [comment]
I am using kali to generate payload for MacOS. Looks like I am doing wrong. Do I need to execute genCrossC2 from MacOS if I want generate payload for MacOS?
./genCrossC2.Linux domain 443 .cobaltstrike.beacon_keys ";;path to profile" MacOS x64 beacon.out

**Comment by raghavmishra** [comment]
Also, I have tried the GUI version as well but the payload is not being generated to /tmp/.

**Comment by raghavmishra** [comment]
When I ran it on Mac, getting segfalut.
![Screenshot 2024-03-01 at 8 37 23 PM](https://github.com/gloxec/CrossC2/assets/3175190/baed3d27-b62a-48d1-ba97-627f974ef3c4)

**Comment by gloxec** [comment]
> Do I need to execute genCrossC2 from MacOS if I want generate payload for MacOS? 

It is not necessary. Running `genCrossC2` on every platform can generate payloads for all system architectures.


> Also, I have tried the GUI version as well but the payload is not being generated to /tmp/.

When it cannot run normally on the `GUI`, you can first output the `CLI command prompt` according to the console and test it in the `CLI`.


> When I ran it on Mac, getting segfalut.

The problem may be:
1. It may be the mac Ventura version, it is a known issue: https://github.com/gloxec/CrossC2/issues/190, need to be repaired first
```
$ brew install upx
$ upx -d genCrossC2
```
2. It may be blocked by mac's gatekeeper security
```
# xattr -c genCrossC2
```

**Comment by raghavmishra** [comment]
Mine is Mac Sonoma.

**Comment by gloxec** [comment]
> Mine is Mac Sonoma.

try same operation: 
```
$ brew install upx
$ upx -d genCrossC2
```

**Comment by raghavmishra** [comment]
I have unpacked it. When I run the payload I don't see any traffic being sent to listener. Maybe it is not working on sonoma.
![Screenshot 2024-03-06 at 2 00 18 PM](https://github.com/gloxec/CrossC2/assets/3175190/89af007b-b0fc-4e96-be3c-d7dbc8cbf84a)

**Comment by raghavmishra** [comment]
Maybe the issue with the latest build of MacOS Sonoma and CS 4.9.1.

**Comment by gloxec** [comment]
on this system version, you need to manually specify not to use `upx` compression when generating beacon

`$./genCrossC2.MacOS 127.0.0.1 443 key ';;c2profile.profile' MacOS x64 ./mac.out raw`

**Comment by raghavmishra** [comment]
It worked.
