### ISSUE TITLE
Linux 结果长度限制

### ISSUE THREAD

**Issue by badboycxcc** [gloxec/CrossC2#225]
不管执行命令还是上传下载文件，只要内容长度太长都会失败，这是什么原因？

**Comment by gloxec** [comment]
可能是c2profile相关的功能导致的，具体需要了解
---
1. cs版本
2. crossc2版本
3. c2profile情况
4. c2连接网络情况 (cdn/nginx/...)
5. beacon生成方式

**Comment by badboycxcc** [comment]
现在是有概率返回信息

**Comment by badboycxcc** [comment]
感觉可能是受网络影响原因（之前丢包了），现在又可以了。
