### ISSUE TITLE
genCrossC2 broken

### ISSUE THREAD

**Issue by CodeXTF2** [gloxec/CrossC2#23]
[root@kali:src]# ./genCrossC2.Linux 127.0.0.1 4444 null null MacOS x64 ./CrossC2-test

Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
read keys error
Exception in thread "main" java.lang.NoClassDefFoundError: common/CommonUtils
        at genKey.BeaconKey.main(BeaconKey.java:52)
Caused by: java.lang.ClassNotFoundException: common.CommonUtils
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 1 more
*[error] : read key error

**Comment by gloxec** [comment]
copy CrossC2.cna and genCrossC2 file to CobaltStrike's rootdir (Must be in the same directory )

[wiki - install](https://gloxec.github.io/CrossC2/en/install/)

issue: #1

**Comment by CodeXTF2** [comment]
That error was produced when I executed the genCrossC2.Linux file manually, the cna shouldnt matter right?

**Comment by gloxec** [comment]
Whether it is directly run or **cna** mode, it needs to be placed in the root directory of cs.

**Comment by CodeXTF2** [comment]
Ok it generated this time, but im not getting a beacon connection. Im seeing this error in my teamserver.

[-] Dropped HTTP client from /192.168.61.185 (malformed header)

Any ideas?
Thanks so much for the help :D

**Comment by CodeXTF2** [comment]
Thanks so much for the help!
It compiled this time but im not getting a beacon from my own kali box. Any ideas?

**Comment by gloxec** [comment]
Are you saying that you haven't gone online after running beacon? Or is there no beacon generated? If it is the former, you need to pay attention to whether the listener is selected correctly (https), whether you use a custom c2profile (you can view the return information on the weblog and teamserver)? If it is the latter, it may still not be installed and used correctly, please refer to the wiki control The following steps, generally manual operation is normal, it means that there is no problem with the configuration.

**Comment by CodeXTF2** [comment]
I have tested it on default configuration using http listener, beacon seems to try to connect to my teamserver but it doesnt show up in cobalt strike.

**Comment by gloxec** [comment]
For the time being, only **https** is supported. The next version will support various custom protocols (c2profile http, tcp, udp, ...), and will be updated very soon.

**Comment by CodeXTF2** [comment]
ohh ok thanks!
