### ISSUE TITLE
use CrossC2.cna  Version1.2 ，load  error

### ISSUE THREAD

**Issue by markhacker** [gloxec/CrossC2#24]
When I use version 1.0，i can use it
but use version1.2 CrossC2.cna，load error
![image](https://user-images.githubusercontent.com/22837681/82125748-b6936880-97da-11ea-8590-57c04e82fe9b.png)
![image](https://user-images.githubusercontent.com/22837681/82125765-c6ab4800-97da-11ea-91d1-a317d61c882d.png)
![image](https://user-images.githubusercontent.com/22837681/82125778-e2aee980-97da-11ea-9f11-31a17686c702.png)

**Comment by gloxec** [comment]
Sorry, just updated **cna** about this issue.

**Comment by gloxec** [comment]
And currently only supports the last bug fixs version of cs 3.14.
