### ISSUE TITLE
支持cobalt4.0吗？

### ISSUE THREAD

**Issue by Dawson0x00** [gloxec/CrossC2#27]
支持cobalt4.0吗？

**Comment by gloxec** [comment]
目前不支持，但将在后续版本中添加4.0分支。

**Comment by Dawson0x00** [comment]
以后趋势慢慢都是cobalt4.0 希望大佬可以尽快更新 嘿嘿～

**Comment by gloxec** [comment]
哈哈，会更新的，变动不大所以需要改动的比较少，目前还是把重心放在了后渗透这边。比如痕迹的隐藏，交互式的shell，以及横向渗透Win/Linux/Mac，以及与三方自定义的shell集连的协议，应对内网各种网络环境及红队习惯或自己开发的shell节点联动。功能实现基本已经完善，在修复些小问题，后续会更新到4.0上去。

**Comment by Dawson0x00** [comment]
哈哦～坐等更新

**Comment by HeiFl** [comment]
+1

**Comment by chriskaliX** [comment]
+1

**Comment by gloxec** [comment]
新分支已支持cs4.1
