### ISSUE TITLE
执行命令没有回显示

### ISSUE THREAD

**Issue by zzywings** [gloxec/CrossC2#28]
请问作者，我机器上线后，执行命令没有回显是什么情况

**Comment by gloxec** [comment]
使用的是3.14最后一个bug修复版本吗？

**Comment by rockmelodies** [comment]
![image](https://user-images.githubusercontent.com/24653177/86813448-c6307e80-c0b2-11ea-969f-e9cccf4b06f5.png)
请问最后解决了吗，我用的是这个版本但还是不行

**Comment by gloxec** [comment]
> ![image](https://user-images.githubusercontent.com/24653177/86813448-c6307e80-c0b2-11ea-969f-e9cccf4b06f5.png)
> 请问最后解决了吗，我用的是这个版本但还是不行

这个版本是正确的，有没有具体的系统版本信息，以及cs中weblog信息和teamserver输出的信息呢？

**Comment by rockmelodies** [comment]
[200707.zip](https://github.com/gloxec/CrossC2/files/4886203/200707.zip)

这是所有日志

**Comment by rockmelodies** [comment]
![image](https://user-images.githubusercontent.com/24653177/86818324-d186a880-c0b8-11ea-8212-3258f22ae3d6.png)

**Comment by rockmelodies** [comment]
请问一下 linux 文件管理用不了 是需要什么脚本吗，部分linux becon 执行命令可用

**Comment by zzywings** [comment]
> 使用的是3.14最后一个bug修复版本吗？

附件是我用ubuntu进行实验时候的一些信息。
如果是版本问题，作者能提供一下有用的版本吗
[172.19.0.1.zip](https://github.com/gloxec/CrossC2/files/4887699/172.19.0.1.zip)

**Comment by gloxec** [comment]
> > 使用的是3.14最后一个bug修复版本吗？
> 
> 附件是我用ubuntu进行实验时候的一些信息。
> 如果是版本问题，作者能提供一下有用的版本吗
> [172.19.0.1.zip](https://github.com/gloxec/CrossC2/files/4887699/172.19.0.1.zip)

根据你提供的信息来看，是因为版本问题，请使用3.14 bug fixes版本
