### ISSUE TITLE
becan 文件管理，端口扫描 都用不了，部分命令执行可以

### ISSUE THREAD

**Issue by rockmelodies** [gloxec/CrossC2#29]
![image](https://user-images.githubusercontent.com/24653177/86857829-f0556100-c0f1-11ea-902c-c1035145625b.png)

**Comment by gloxec** [comment]
根据你提供的日志来看，运行是正常的，但是部分命令是Win独有的，因为内置的指令比如screenshot & portscan & logonpasswords等其实是传输exe / dll供beacon执行，所以目标Linux & MacOS无法执行

**Comment by gloxec** [comment]
但文件管理应该是正常的，是否是因为sleep 时间过久导致信息回传过慢所以你没有看到？
端口扫描功能可使用CrossC2-kit中提供的cc2_portscan & cc2_serverscan功能
