### ISSUE TITLE
自定义通信协议能提供一份示例test.c文件吗

### ISSUE THREAD

**Issue by xxxx-stack** [gloxec/CrossC2#31]
自己参照[通信模板](https://gloxec.github.io/CrossC2/zh_cn/protocol/)相关部分的说明编译的lib_rebind_test.so，并在profile文件中增加了相应调整的url，但是无法正常上线，希望师傅能提供一份完整的关于自定义通信模板的文件。谢谢

**Comment by gloxec** [comment]
@xxxx-stack  已添加了一份c2profile以及协议重绑定的范例
