### ISSUE TITLE
请问支持linux平台域名上线功能吗？

### ISSUE THREAD

**Issue by 67348285** [gloxec/CrossC2#35]
为何使用./genCrossC2.Linux www.xxx.com 443 null null Linux x64 ./c2.elf生的可执行文件，不能上线？/genCrossC2.Linux 目前不支持host 为域名吗？

**Comment by gloxec** [comment]
暂时不支持，已将该问题加入下个版本的更新方案中

**Comment by gloxec** [comment]
现已支持
https://github.com/gloxec/CrossC2/releases/tag/v2.2
