### ISSUE TITLE
为什么使用cs4.1能上线但是无法执行命令呢？

### ISSUE THREAD

**Issue by striveben** [gloxec/CrossC2#38]
大佬好：
下载的cross2的2.1版本，在cs4.1下能上线，但是没法执行命令，这是怎么回事呢？请指教。
![image](https://user-images.githubusercontent.com/61238912/98689454-eb0d6900-23a6-11eb-9002-fb0e94f59578.png)
![image](https://user-images.githubusercontent.com/61238912/98689485-f365a400-23a6-11eb-838c-5b7ddd20348d.png)
而且上线的internal地址很奇怪：
![image](https://user-images.githubusercontent.com/61238912/98689780-36c01280-23a7-11eb-9232-ce136991eb33.png)

**Comment by yumusb** [comment]
https://github.com/gloxec/CrossC2/tree/cs4.1/src
用4.1分支里的。

**Comment by striveben** [comment]
哦哦，谢谢。
