### ISSUE TITLE
请问生成移动端 beacon 的 cna 文件在哪儿？

### ISSUE THREAD

**Issue by NickYan7** [gloxec/CrossC2#39]
想测试一下 iOS/Android 的移动端 beacon 上线情况，但是在 release V2.1 版本中的 cna 文件只有生成 Linux/macOS/linux-bind/macOS-bind 四种选项，请问移动端测试的脚本文件在哪里呢？感谢！

**Comment by gloxec** [comment]
这个功能因为一些打包问题计划后续再更新，脚本中暂时无法添加此功能

**Comment by we1x4n** [comment]
cna无法调用，若是直接使用二进制文件可以生成？

**Comment by gloxec** [comment]
@we1x4n 因为移动端的是dylib & so动态库形式，目前的生成器无法打包动态库，解决后准备和正常主机端一起推动态库生成方式。在解决动态库加载问题同时，也可用于进程注入相关功能。
