### ISSUE TITLE
使用GUI生成无法上线

### ISSUE THREAD

**Issue by yhy0** [gloxec/CrossC2#40]
[-] Beacon entry did not validate
        internal address 'ssh-Linux' is not an address
[-] Session 842348593 -> Beacon @805908790, 0ms metadata validation failed. Dropping
[-] A Malleable C2 attempt to recover data from a '.http-get.client.metadata' transaction failed. This could be due to a bug in the profile, a change made to the profile after this Beacon was run, or a change made to the transaction by some device between your target and your Cobalt Strike controller. The following information will (hopefully) help narrow down what happened.
![image](https://user-images.githubusercontent.com/31311038/99023561-cd572400-259f-11eb-9225-424c39c412f4.png)

![image](https://user-images.githubusercontent.com/31311038/99023432-95e87780-259f-11eb-9c41-286b3f09fdea.png)

**Comment by yhy0** [comment]
cs4.0

**Comment by gloxec** [comment]
4.0 暂不支持，请使用cs4.1

**Comment by gloxec** [comment]
4.0分支已更新
