### ISSUE TITLE
使用cs4.0 GUI生成的不能上线，使用的4.0分支

### ISSUE THREAD

**Issue by yhy0** [gloxec/CrossC2#41]
![image](https://user-images.githubusercontent.com/31311038/99340985-0525da80-28c4-11eb-97e5-71031f035762.png)
![image](https://user-images.githubusercontent.com/31311038/99341417-c80e1800-28c4-11eb-934b-dbb88d6d8093.png)

**Comment by gloxec** [comment]
cna中genCrossC2的路径是否替换为4.0分支新下的呢？还有你的cs4.0版本hash是哪个呢？有两个版本

 Cobalt Strike 4.0 (February 22, 2020) [bug fixes]
10fe0fcdb6b89604da379d9d6bca37b8279f372dc235bbaf721adfd83561f2b3	Cobalt Strike 4.0 Licensed (cobaltstrike.jar)

Cobalt Strike 4.0 (December 5, 2019)
558f61bfab60ef5e6bec15c8a6434e94249621f53e7838868cdb3206168a0937	Cobalt Strike 4.0 Licensed (cobaltstrike.jar)

**Comment by yhy0** [comment]
替换了，cs是2019年的

**Comment by yhy0** [comment]
![image](https://user-images.githubusercontent.com/31311038/99356496-382c9600-28e5-11eb-8fbd-ae1d241b4237.png)
我从4.0分支重新下载使用，GUI不能生成

**Comment by gloxec** [comment]
2019那个版本测试了下是可以正常使用的。
GUI失败的话，使用命令行生成的也不可以吗

**Comment by yhy0** [comment]
我使用命令行在kali下可以生成，能正常上线，感谢大佬
