### ISSUE TITLE
cs 4.1无法执行命令

### ISSUE THREAD

**Issue by AdministratorGithub** [gloxec/CrossC2#43]
能上线，无法执行命令
![image](https://user-images.githubusercontent.com/19834937/99616870-089e9a80-2a59-11eb-979f-f9a4d44702ec.png)

**Comment by gloxec** [comment]
使用的是cs4.1分支中的吗？

**Comment by AdministratorGithub** [comment]
误报，未更换之前版本，已成功

**Comment by DmmusOT08762** [comment]
大神。付费咨询，能不能给个联系方式？

**Comment by badboycxcc** [comment]
![image](https://user-images.githubusercontent.com/72059221/100334867-48dcba80-300f-11eb-9b0e-6b6b5d544c4b.png)
使用版本是 release v2.1

**Comment by gloxec** [comment]
@badboycxcc 你看看是否是修改脚本前后字符没有闭合，本地测试cna是正常的
