### ISSUE TITLE
CS4.1 linux被判断成为windows主机，无法执行命令。

### ISSUE THREAD

**Issue by badboycxcc** [gloxec/CrossC2#44]
![image](https://user-images.githubusercontent.com/72059221/100054245-aed51080-2e5c-11eb-8c4b-cfcf024621fc.png)
![image](https://user-images.githubusercontent.com/72059221/100054326-cad8b200-2e5c-11eb-9bf1-3eb4bb14ce0c.png)
![image](https://user-images.githubusercontent.com/72059221/100054357-d3c98380-2e5c-11eb-849a-af5c544cbcf5.png)

**Comment by gloxec** [comment]
应该是下载的版本有问题，尝试下4.1分支的

**Comment by DmmusOT08762** [comment]
大神，可以加你联系方式吗？商务合作。我邮箱macdaidvlsyij8140@gmail.com

**Comment by gloxec** [comment]
抱歉，该项目用于企业针对自身安全的红队评估项目 @DmmusOT08762

**Comment by DmmusOT08762** [comment]
不是这个问题  付费咨询

**Comment by DmmusOT08762** [comment]
商务有偿咨询可吗？
