### ISSUE TITLE
请问支持cobaltstrike4的自定义的Malleable-C2-Profile么？

### ISSUE THREAD

**Issue by orleven** [gloxec/CrossC2#45]
请问支持cobaltstrike4的自定义的Malleable-C2-Profile么？

**Comment by gloxec** [comment]
支持的，稍后我上传一份完整的demo实例。
不过windows版本的genCrossC2收到反馈自定义协议有问题，会失效，建议暂时使用Linux & MacOS版本，测试这两个是正常的

**Comment by gloxec** [comment]
@orleven 参照 https://github.com/gloxec/CrossC2/blob/master/protocol_demo/c2profile.c 与对应的c2profile去编写你自己的profile动态库，编译后在生成时选择动态库即可

**Comment by orleven** [comment]
好的，目前是只支持demo里的这几个预留的api，其他的还不支持对吗？

**Comment by gloxec** [comment]
和其它分支一样，支持完整的HTTPs通信模版的更改与自定义通信协议，具体可以参考 [通信协议API](https://gloxec.github.io/CrossC2/zh_cn/protocol/)

**Comment by orleven** [comment]
ok，搞定了～谢谢
