### ISSUE TITLE
windows10下genCrossC2.Win.exe生成报错

### ISSUE THREAD

**Issue by liler1** [gloxec/CrossC2#50]
请问是什么问题呢。
![image](https://user-images.githubusercontent.com/71866537/102764292-e67c9d00-43b5-11eb-84cf-08564502cf1a.png)

![image](https://user-images.githubusercontent.com/71866537/102764580-51c66f00-43b6-11eb-8d8e-03cd2ee8228b.png)

**Comment by gloxec** [comment]
参考 https://github.com/gloxec/CrossC2/issues/49#issuecomment-748630879 解决方法

**Comment by liler1** [comment]
谢谢老大，可以了！
