### ISSUE TITLE
cs 4.0版本命令执行无回显

### ISSUE THREAD

**Issue by st-lucifer** [gloxec/CrossC2#51]
4.0版本的cs，使用4.0分支的脚本，执行命令无回显。
![image](https://user-images.githubusercontent.com/17016792/102954035-99134380-450d-11eb-9740-767370c84f54.png)

**Comment by gloxec** [comment]
参见这里，确定下cs版本 https://github.com/gloxec/CrossC2/issues/41#issuecomment-728660705

**Comment by st-lucifer** [comment]
> 参见这里，确定下cs版本 [#41 (comment)](https://github.com/gloxec/CrossC2/issues/41#issuecomment-728660705)

大佬，你那个hash是哪种算法啊？我这边sha256算出来的值比你给的多一位啊。而且都不一样。。。

**Comment by gloxec** [comment]
这个是官方发布, SHA-256
https://verify.cobaltstrike.com/

如果无法比对的话，可以在About中查看发布时间，版本说明等信息

**Comment by st-lucifer** [comment]
> 这个是官方发布, SHA-256
> https://verify.cobaltstrike.com/

大佬，我明白了。我用的是pj版。。。hash确实对不上[悲剧]，cracked版的。那我是不是应该再重新下一下4.0分支的？

**Comment by gloxec** [comment]
查看Help-> About确认下发布日期来比对下版本

**Comment by st-lucifer** [comment]
19年的
![image](https://user-images.githubusercontent.com/17016792/102970479-8828f900-4532-11eb-9649-66113ea37ce8.png)

**Comment by gloxec** [comment]
这个版本的目前测试是正常的，是否有其它资源的同版本cs进行过尝试呢？

**Comment by st-lucifer** [comment]
> 这个版本的目前测试是正常的，是否有其它资源的同版本cs进行过尝试呢？

我重新下载了一下4.0版本的文件，然后就好了，估计是当时下载错了，用的是master。
谢谢大佬
