### ISSUE TITLE
./genCrossC2.Linux: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by ./genCrossC2.Linux)

### ISSUE THREAD

**Issue by Corgizz** [gloxec/CrossC2#52]
Centos 7.x 

GLIBC_2.25 这个库太难安装了

运行报错
./genCrossC2.Linux: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by ./genCrossC2.Linux)

**Comment by gloxec** [comment]
2.25版本的glibc是很老的底层库了，出现这个问题是因为centos系列的系统底层库版本一般都比较低，可以考虑使用新版或者其它unix系统。
不过后续会考虑生成器会使用低版本系统进行编译。

**Comment by Corgizz** [comment]
好的，谢谢了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hooooooooooook"<notifications@github.com&gt;; 
发送时间: 2020年12月24日(星期四) 中午11:27
收件人: "gloxec/CrossC2"<CrossC2@noreply.github.com&gt;; 
抄送: "十八"<812358080@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [gloxec/CrossC2] ./genCrossC2.Linux: /lib64/libc.so.6: version `GLIBC_2.25&#39; not found (required by ./genCrossC2.Linux) (#52)





 
2.25版本的glibc是很老的底层库了，出现这个问题是因为centos系列的系统底层库版本一般都比较低，可以考虑使用新版或者其它unix系统。
 不过后续会考虑生成器会使用低版本系统进行编译。

**Comment by gloxec** [comment]
已支持
https://github.com/gloxec/CrossC2/releases/tag/v2.2

**Comment by Corgizz** [comment]
感谢师傅




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hooooooooooook"<notifications@github.com&gt;; 
发送时间: 2021年1月20日(星期三) 晚上8:21
收件人: "gloxec/CrossC2"<CrossC2@noreply.github.com&gt;; 
抄送: "十八"<812358080@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [gloxec/CrossC2] ./genCrossC2.Linux: /lib64/libc.so.6: version `GLIBC_2.25&#39; not found (required by ./genCrossC2.Linux) (#52)





 
已支持
 https://github.com/gloxec/CrossC2/releases/tag/v2.2

**Comment by chenyu349** [comment]
是需要更换centos8.0以上吗？
