### ISSUE TITLE
3.13版本CS可以正常上线但无法执行命令

### ISSUE THREAD

**Issue by Forthrglory** [gloxec/CrossC2#53]
如题，CS版本为3.13，部署在云服务器上
![version.png](https://i.loli.net/2020/12/23/1H3qOg5r7NWYRAV.png)
按照文档修改了路径并拷贝了keys文件，生成了木马文件并运行，能够成功上线，但是上线后执行任何命令都收不到返回数据
![ssh.png](https://i.loli.net/2020/12/23/bRuxzLfZAjipg1N.png)
目标靶机是无论是利用互联网上的服务器进行测试还是本地虚拟机测试都无法执行命令
请问是我哪里没有配置好还是其他原因导致的

**Comment by gloxec** [comment]
文档介绍中有写暂时只支持cs 3.14(bug fixes), 4.0, 4.1这三个版本

**Comment by Forthrglory** [comment]
> 文档介绍中有写暂时只支持cs 3.14(bug fixes), 4.0, 4.1这三个版本

好的，十分感谢，看错了，以为是支持到3.14的版本
