### ISSUE TITLE
windows安装为什么一直失败

### ISSUE THREAD

**Issue by dengxmenglihua** [gloxec/CrossC2#56]

**Comment by gloxec** [comment]
参考是否为该问题: https://github.com/gloxec/CrossC2/issues/49
以及解决方案: https://github.com/gloxec/CrossC2/issues/49#issuecomment-748630879

**Comment by dengxmenglihua** [comment]
我是cs4.1的版本，linux成功上线到cs上，但不能执行命令，这是为什么呢

**Comment by gloxec** [comment]
用的是4.1分支吗，master分支是3.14版本的

**Comment by dengxmenglihua** [comment]
![图片](https://user-images.githubusercontent.com/59153500/103398863-6e626400-4b79-11eb-88be-8640138cf7b9.png)

**Comment by dengxmenglihua** [comment]
是cs4.1的

**Comment by gloxec** [comment]
看截图似乎使用的是cs3.14的生成器，请下载这个链接中的生成器 https://github.com/gloxec/CrossC2/tree/cs4.1/src

**Comment by dengxmenglihua** [comment]
我就是用的这个生成器生成的，windows和linux都试着生成了后门，结果是都能上线但都不能执行命令

**Comment by dengxmenglihua** [comment]
![图片](https://user-images.githubusercontent.com/59153500/103399500-5b9d5e80-4b7c-11eb-967f-4f36c329d191.png)

**Comment by dengxmenglihua** [comment]
![图片](https://user-images.githubusercontent.com/59153500/103399623-d4041f80-4b7c-11eb-9e18-3c0edcd9b79a.png)

**Comment by dengxmenglihua** [comment]
![图片](https://user-images.githubusercontent.com/59153500/103399706-4674ff80-4b7d-11eb-84ab-697f73535731.png)

**Comment by gloxec** [comment]
因为从截图的会话来看的话4.1不可能出现windows图标。
4.x开始的分支强制移除了windows标志，以及note & process都是不存在的，pid被与主机名合并到了一起。
4.x会话的主机名改为了 hostname(pid)方式，例如kali(113)这样，单从截图来看应该是3.14的生成器。

请确认下生成器的版本，如果还有异常的话，确认下cs版本（cs查看Help-> About确认下发布日期），以及weblog & teamserver 输出的报错信息。

**Comment by gloxec** [comment]
相似问题参见： https://github.com/gloxec/CrossC2/issues/51#issuecomment-750015360

**Comment by dengxmenglihua** [comment]
![Uploading image.png…]()

**Comment by dengxmenglihua** [comment]
![image](https://user-images.githubusercontent.com/59153500/103401445-c9995400-4b83-11eb-944d-94d0292cfe4f.png)

**Comment by dengxmenglihua** [comment]
大佬，成功了，谢谢大佬

**Comment by dengxmenglihua** [comment]
666
