### ISSUE TITLE
glibc版本过高

### ISSUE THREAD

**Issue by ssrsec** [gloxec/CrossC2#57]
cs4.1，Linux生成的时候，报/root/cs/genCrossC2.Linux: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /root/cs/genCrossC2.Linux)

服务端glibc为2.17的

**Comment by gloxec** [comment]
相同问题参见: https://github.com/gloxec/CrossC2/issues/52
设计时未考虑服务端使用生成器，下个版本的生成器将采用低版本系统进行编译

**Comment by gloxec** [comment]
已支持
https://github.com/gloxec/CrossC2/releases/tag/v2.2
