### ISSUE TITLE
kali 5.3.0运行报错

### ISSUE THREAD

**Issue by richard0day** [gloxec/CrossC2#6]
hook大佬
在kali中直接命令行使用，命令如下：
`./genCrossC2 172.16.39.212 8080 null null Linux x64 ./shell`
运行后报错：
```
munmap_chunk(): invalid pointer
已放弃
```

**Comment by richard0day** [comment]
使用命令
`./genCrossC2 127.0.0.1 4444 null null MacOS x64 ./shell`
运行后报错
```
free(): invalid size
已放弃
```

**Comment by gloxec** [comment]
新版本已修复Kali运行时的该错误

**Comment by cx-reboot** [comment]
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
double free or corruption (out)
已放弃

**Comment by gloxec** [comment]
能否给出运行环境信息，如genCrossC2版本，操作系统，jdk版本等，以及是否将server上的.beaconkey拷贝到本地？

**Comment by cx-reboot** [comment]
好的大佬。
java 环境 Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
OS: Kali Linux 
Kernel: x86_64 Linux 5.4.0-kali3-amd64
是本地测试搭建的。

**Comment by gloxec** [comment]
> java 环境 Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
> OS: Kali Linux
> Kernel: x86_64 Linux 5.4.0-kali3-amd64

针对这个环境的测试无任何报错，看看使用方法有没有参照README或者确认使用的是否是最新版本的release
