### ISSUE TITLE
Cross C2 CS4.0 功能缺失

### ISSUE THREAD

**Issue by thinkycx** [gloxec/CrossC2#63]
环境：
CS4.0
Cross C2 4.0 branch

缺少了基本的：文件查看等功能。

上线后的效果：
![image](https://user-images.githubusercontent.com/13138128/106254885-33c11980-6254-11eb-8ff6-42f1bccdda49.png)

**Comment by gloxec** [comment]
下载分支对应目录
https://github.com/gloxec/CrossC2/tree/cs4.0/CrossC2Kit
加载 `CrossC2Kit_Loader.cna` 即可

但建议使用cs4.1分支下的CrossC2 及 CrossC2 Kit，拥有更多的功能及更稳定（修复大量长期使用后反馈的各类潜在问题)。
4.1分支支持 cs版本 >= 4.1，以及内存加载持续化调用等新功能，后期会支持进程注入等等。
3.14 & 4.0 分支已暂停更新支持。

**Comment by thinkycx** [comment]
Thanks.
