### ISSUE TITLE
Source code not available

### ISSUE THREAD

**Issue by Stoo0rmq** [gloxec/CrossC2#64]
The initial requirement defined as:

_Only for internal use by enterprises and organizations, this framework has a certain degree of instability. Non-professionals are not allowed to use it_

Does not match with almost any security policy of running unverified code on their internal organization.  It would be helpful if the full source code would be available.

No one should ever execute closed code provided from an untrusted source.

**Comment by gloxec** [comment]
Just for legal risk warning.

> The initial requirement defined as:
> 
> > _Only for internal use by enterprises and organizations, this framework has a certain degree of instability. Non-professionals are not allowed to use it_

The code is still being refactored. Or will be submitted later.
