### ISSUE TITLE
Cobaltstrike4.0 CrossC2无法上线

### ISSUE THREAD

**Issue by Jameszjm** [gloxec/CrossC2#67]
客户端、服务端都在Linux上，使用genCrossC2.Linux生成了Linxu木马，执行后结束无任何回显，无看到主机上线

**Comment by gloxec** [comment]
是使用的4.0分支吗？ https://github.com/gloxec/CrossC2/tree/cs4.0

**Comment by Jameszjm** [comment]
我下的是v2.1

**Comment by gloxec** [comment]
releases中 v2.1及以前都是cs [3.14(最后一版)](https://verify.cobaltstrike.com/)
<img width="935" alt="image" src="https://user-images.githubusercontent.com/5158011/112108518-41a77100-8beb-11eb-8d76-1c6748027f19.png">

v2.2 开始都是4.x ( >= cs4.1 )
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/5158011/112108493-381e0900-8beb-11eb-9f48-035ee3c71cc1.png">

cs4.0只能从分支中下载,可以使用 `svn co https://github.com/gloxec/CrossC2/branches/cs4.0/src/` 进行下载

**Comment by Jameszjm** [comment]
解决了，Linux下启动客户端可以生成马，上线，执行操作；Windows启动客户端下已修改CrossC2.cna的路径参数，没生成CrossC2的木马文件

**Comment by gloxec** [comment]
> ... Windows启动客户端下已修改CrossC2.cna的路径参数，没生成CrossC2的木马文件

可先cmd中运行genCrossC2.win.exe，查看是否正常运行，如果报错缺少DLL信息，可参考文档中的 `注意事项⚠️`
https://github.com/gloxec/CrossC2/blob/cs4.1/README_zh.md#install--usage

可能相似的问题: #50 , https://github.com/gloxec/CrossC2/issues/49#issuecomment-748630879

**Comment by Jameszjm** [comment]
cc2_auth                  CrossC2 auth rootkit - Get password for auth action(sshd/sudo/su/passwd...).
    cc2_frp                   CrossC2 proxy frp  -  Start Linux/MacOS SOCKS5 proxy {TCP/KCP(UDP)}
    cc2_iMessage_dump         CrossC2 iMessage dump - dump message from iMessage.
    cc2_job                   CrossC2 joblist - Manage running tasks
    cc2_keychain_dump         CrossC2 Keychain dump (root) - dump login username & password from Keychain.
    cc2_keylogger             CrossC2 keylogger - listen to the string entered by the user from the keyboard.
    cc2_mimipenguin           CrossC2 mimipenguin - dump the login password from the current linux desktop
    cc2_portscan              CrossC2 PortScan(1.1M) - Scan a network for open services, but it will be seen in the process
    cc2_portscan_dyn          CrossC2 PortScan Dyn(3.8M) - Scan a network for open services
    cc2_prompt_spoof          CrossC2 prompt_spoof - (AppStore) interface pops up and prompts the user to enter a password, stealing the entered password
    cc2_safari_dump           CrossC2 safari dump - dump browser history from Safari(default 500).
    cc2_script                CrossC2 Script - run scripts in memory
    cc2_serverscan            CrossC2 ServerScan(3M) - Scan a network for open services and services version detection,  but it will be seen in the process
    cc2_serverscan_dyn        CrossC2 ServerScan Dyn(9.8M) - Scan a network for open services and services version detection
    cc2_ssh                   CrossC2 SSH rootkit - Get password for ssh login.






ssh> cc2_job linux list all
[+] cc2_job: 
[*] Tasked beacon to upload CrossC2^1^cc2_jobjzCF^info^27048^bGlzdF5hbGw= as CrossC2^1^cc2_jobjzCF^info^27048^bGlzdF5hbGw=
[+] host called home, sent: 27105 bytes
[+] received output:

---------- job list ----------
job Name : cc2_mimipenguinZtXA
job PID : 4040230

job Name : cc2_portscanHYZR
job PID : 4126390

job Name : cc2_portscanABei
job PID : 284986

job Name : cc2_portscanKyVQ
job PID : 296832

job Name : cc2_serverscanMEwe
job PID : 644351


[+] received output:




试了几个功能，卡在“[+] received output:”这一步后没有显示了

**Comment by gloxec** [comment]
> ---------- job list ----------
> job Name : cc2_mimipenguinZtXA
> job PID : 4040230

从job PID来看这里似乎是异常的，应该没有正常启动，请问CrossC2Kit插件是从哪个地方下载的呢？也是从4.0分支获取的吗？

**Comment by Jameszjm** [comment]
确实是从4.0分支下的，能上线，能执行CS内置命令ps、shell、help等等。但是CrossC2Kit的功能不行，又如cc2_portscan功能，停留在了[+] received output:


ssh> cc2_portscan linux 192.168.10.252 1-65535 tcp
[+] cc2_serverscan: 192.168.10.252 1-65535 tcp
[*] Tasked beacon to upload CrossC2^0^cc2_portscanIRVT^portscan^3799080^MTkyLjE2OC4xMC4yNTJeMS02NTUzNV50Y3A= as CrossC2^0^cc2_portscanIRVT^portscan^3799080^MTkyLjE2OC4xMC4yNTJeMS02NTUzNV50Y3A=
[+] host called home, sent: 1046712 bytes
[+] host called home, sent: 1040752 bytes
[+] host called home, sent: 1040752 bytes
[+] host called home, sent: 672060 bytes
[+] received output:

**Comment by gloxec** [comment]
portscan功能在2.2之前是有问题的，具体细节可见 https://github.com/gloxec/CrossC2/issues/61#issuecomment-767264316 处的描述。
该问题仅在cs4.1分支进行了修复，commit详见https://github.com/gloxec/CrossC2/commit/c67e20eba8867cbcee09c204d07c11a5c703620d
因为cs较多版本的问题，无力进行其它分支的维护(3.14-master, 4.0)，可尝试比较上述commit中修改过的内容进行更正。

**Comment by gloxec** [comment]
建议还是使用cs >= 4.1版本，低版本的从v2.2开始不再维护  https://github.com/gloxec/CrossC2/blob/cs4.1/README_zh.md#changelog

**Comment by gloxec** [comment]
目前内置的serverscan由 @Trim 提供，具体用法可见对应项目的详细介绍： https://github.com/Adminisme/ServerScan#for-cobalt-strike , 可手动加载插件进行使用。
