### ISSUE TITLE
Open source for beacon generation binaries

### ISSUE THREAD

**Issue by HellooTiger** [gloxec/CrossC2#68]
Great Work! Do you have any plan to make these beacon generation binaries open source, such as genCrossC2.Linux.

**Comment by gloxec** [comment]
Yes, these will be open source after code refactoring. At first, the project was only used for emergency and temporary use of the project, so in order to realize the function, the standardization of the project was not considered. For example, the code of a single file reaches several thousand lines, which will cause a lot of trouble in the collaborative development of multiple people and reading.

**Comment by gloxec** [comment]
If you are currently interested in the low-level details related to cs, you can refer to our partner's project [geacon](https://github.com/darkr4y/geacon)

**Comment by HellooTiger** [comment]
OK, Understood.  I'll dig into the geacon project, and find out these low-level details. The need of open source these beacon generating binaries is for customization, since users may tailor a beacon to suite different c2 profiles at the absence of supporting rich C2 profiles which is declared to be comming soon. BTW, supporting rich C2 profiles is desperately wanted.

**Comment by gloxec** [comment]
CrossC2 uses a communication protocol rebinding scheme to support c2profile.
wiki: https://gloxec.github.io/CrossC2/en/protocol/

It is very easy to implement different c2profile support, just need to change some HTTP request `URI & Headers` and locate the string before and after the `metadata`.
demo: https://github.com/gloxec/CrossC2/blob/cs4.1/protocol_demo/c2profile.c

And through the provided API, you can simply realize the TCP/UDP way back connection.
https://github.com/gloxec/CrossC2/blob/cs4.1/protocol_demo/rebind_udp.c

**Comment by HellooTiger** [comment]
These definitely solve my issue.

**Comment by hdbreaker** [comment]
Hey guys, I'm not been able to create a c2profile.c that works with my simple profile... can you help me with that please?
I already read all the documentation but It does not work and I'm not been hable to totally understand the process.

My c2 profile looks like the following:

```
http-config {
    set trust_x_forwarded_for "true";
}

http-get {
    set uri "/get";
    client {
        header "AUTH_TOKEN" "MY_TOKEN";

        metadata {
            base64url;
            netbios;
            base64url;
            parameter "token";
        }
    }

    server {
        header "Content-Type" "application/json; charset=utf-8";
        header "Cache-Control" "no-cache, no-store, max-age=0, must-revalidate";
        header "Pragma" "no-cache";

        output {
            base64;
            prepend "{\"version\":\"2\",\"count\":\"1\",\"data\":\"";
            append "\"}";
            print;
        }
    }
}

http-post {
    set uri "/post";
    set verb "POST";

    client {
        parameter "action" "GetExtensibilityContext";
        header "Content-Type" "application/json; charset=utf-8";
        header "Pragma" "no-cache";
        header "AUTH_TOKEN" "MY_TOKEN";

        id {
            parameter "token";
        }

        output {
            mask;
            base64;
            prepend "{\"version\":\"2\",\"report\":\"";
            append "\"}";
            print;
        }
    }

    server {
        header "api-supported-versions" "2";
        header "Content-Type" "application/json; charset=utf-8";
        header "Cache-Control" "no-cache, no-store, max-age=0, must-revalidate";
        header "Pragma" "no-cache";

        output {
            base64url;
            prepend "{\"version\":\"2\",\"count\":\"1\",\"data\":\"";
            append "\"}";
            print;
        }
    }
}
```

My c2profile.c looks like the following:

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

void cc2_rebind_http_get_send(char *reqData, char **outputData, long long *outputData_len) {
    char *requestBody = "GET /%s HTTP/1.1\r\n"
    "AUHT_TOKEN: MY_TOKEN\r\n";
    char postPayload[20000];
    sprintf(postPayload, requestBody, "get", reqData);

    *outputData_len =  strlen(postPayload);
    *outputData = (char *)calloc(1,  *outputData_len);
    memcpy(*outputData, postPayload, *outputData_len);

}
void cc2_rebind_http_post_send(char *reqData, char *id, char **outputData, long long *outputData_len) {
    char *requestBody = "POST /%s HTTP/1.1\r\n"
        "Content-Type: application/json; charset=utf-8\r\n"
        "Cache-Control: no-cache, no-store, max-age=0, must-revalidate\r\n"
        "Pragma: no-cache\r\n"
        "AUTH_TOKEN: MY_TOKEN\r\n";
        "Connection: close\r\n"
        "Content-Length: %d\r\n\r\n%s";
    char *postPayload = (char *)calloc(1, strlen(requestBody)+strlen(reqData)+200);
    sprintf(postPayload, requestBody, "post", id, strlen(reqData), reqData);

    *outputData_len =  strlen(postPayload);
    *outputData = (char *)calloc(1,  *outputData_len);
    memcpy(*outputData, postPayload, *outputData_len);
    free(postPayload);
}

char *find_payload(char *rawData, long long rawData_len, char *start, char *end, long long *payload_len) {
    
    //find_payload() 从原始数据中，找到以"ffffffff1"字符串开始，"eeeeeeee2"字符串结束中间包含的数据

    // ffffffff1AAAABBBBCCCCDDDDeeeeeeee2 -> AAAABBBBCCCCDDDD

    // *payload_len = xx; // 返回找到的payload长度
    // return payload; // 返回找到的payload

    rawData = strstr(rawData, start) + strlen(start);
    
    *payload_len = strlen(rawData) - strlen(strstr(rawData, end));
    
    char *payload = (char *)calloc(*payload_len ,sizeof(char));
    memcpy(payload, rawData, *payload_len);
    return payload; 
}

void cc2_rebind_http_get_recv(char *rawData, long long rawData_len, char **outputData, long long *outputData_len) {

    char *start = "ffffffff1";
    char *end = "eeeeeeee2";

    long long payload_len = 0;
    *outputData = find_payload(rawData, rawData_len, start, end, &payload_len);
    *outputData_len = payload_len;
}

void cc2_rebind_http_post_recv(char *rawData, long long rawData_len, char **outputData, long long *outputData_len) {

    char *start = "ffffffff1";
    char *end = "eeeeeeee2";

    long long payload_len = 0;
    *outputData = find_payload(rawData, rawData_len, start, end, &payload_len);
    *outputData_len = payload_len;
}
```

**Comment by hdbreaker** [comment]
@gloxec

**Comment by gloxec** [comment]
@hdbreaker 

I saw the following encryption and decryption configuration in your c2profile
```
http-get/post {
 metadata {
            base64url;
            netbios;
            base64url;
 }
 ...
}
```

among them base64url, netbios, mask, etc. are used, but your c2profile.c does not implement these codec functions. The specific sequence of codecs needs to refer to the introduction of Readme.md

There are two options here:
1. (recommend) Choose the latest version of release, which includes automatic analysis of c2profile, no need to pay attention to the specific implementation

    `genCrossC2 www.example.com 443 .cobaltstrike.beacon_keys ";;c2profile.profile" Linux x64 beacon.out`

2. still need to do lower-level traffic customization, you can refer to using ac to automatically generate [autoRebind](https://github.com/CrossC2/autoRebind), which supports all codec algorithms of CobaltStrike

    `autoRebind c2profile.profile > c2profile.c`
