### ISSUE TITLE
win10下使用CS4.2 生成失败，且无错误信息。

### ISSUE THREAD

**Issue by xizyy** [gloxec/CrossC2#70]
事件栏如下，没错误信息
03/31 13:36:43 *** 
03/31 13:38:03 *** 
03/31 13:38:33 *** 
尝试直接用exe生成。可以生成，且能进入beacon执行命令。
判定是cna配置路径出错，一开始我以为是转义问题我分别试了 \\ 、\、/。但是均是一样结果。然后又试了PATH末尾加genCrossC2.Win.exe文件名以及不加，且每种都分别用这三路径\\ 、\、/试了。还是一样。

没办法了，虽然能用但是还是很想用GUI生成。不知是什么原因。PS：使用的是V2.2 Cross,即当前最新版。

**Comment by gloxec** [comment]
可能是路径问题，比如携带了特殊字符，或者空格中文等？最后问题有找到吗

**Comment by xizyy** [comment]
找到了。是路径带了特殊字符。有个&号。
