### ISSUE TITLE
生成payload过程无反应

### ISSUE THREAD

**Issue by s045pd** [gloxec/CrossC2#72]
![image](https://user-images.githubusercontent.com/22721729/113504273-9b078c80-9569-11eb-9b08-c74ec3842f14.png)

- bigSur 11.2.3
- cs4.2

就打印了个日志 ，没继续了
似乎是停在了这段  `$data = readAll($process);`
然后那段命令在本地直接执行又是行的

**Comment by gloxec** [comment]
第一行的 `/xxx/xx/genCrossC2.MacOS 172.16.251.1 5555 /tmp/beacon_keys null MacOS x64 /tmp/CrossC2-test` 提示有出现吗？
如果没有的话，检查cna脚本是否正确，有的话检查是否是路径问题，比如携带空格、中文、或特殊字符导致的

**Comment by s045pd** [comment]
有提示的（突然发现截错图了 - - ），但就是不继续执行

**Comment by gloxec** [comment]
路径中是否包含特殊字符呢？

**Comment by s045pd** [comment]
`~/C2/CrossC2/genCrossC2.MacOS domain.com 443 ~/C2/cobaltstrike.beacon_keys null Linux x64 ~/C2/C2outPut/CrossC2-test 
`
大概是这样了

**Comment by s045pd** [comment]
哎 不知道是某种啥情况无法执行
最后通过py去跑这个就可了

`$process = exec('python -c "import os;os.system(\"'.$genCC2.'\")" ');`

**Comment by gloxec** [comment]
如果这里的~符号只是你为了回复issue做的省略的话，那我也不知道怎么回事，有无尝试修改cna，尝试调用它时不加任何参数去运行呢？
