### ISSUE TITLE
cs4.2  Linux无法上线

### ISSUE THREAD

**Issue by kb-8-byte** [gloxec/CrossC2#74]
1. 生成的payload 成功
2. 运行的时候也一直访问 server 的监听器。但无法上线

![image](https://user-images.githubusercontent.com/18651522/113739875-cee1de00-9732-11eb-8251-ec53667e5b15.png)

**Comment by gloxec** [comment]
这里应该是你配置了c2profile的问题，应该对照着profile中http-get和http-post配置的内容，编写对应的协议重绑定库(设定http头，前后payload搜索字符)
可参考文档:
https://gloxec.github.io/CrossC2/zh_cn/protocol/
demo:
https://github.com/gloxec/CrossC2/blob/cs4.1/protocol_demo/https.profile
https://github.com/gloxec/CrossC2/blob/cs4.1/protocol_demo/c2profile.c
相似问题:
https://github.com/gloxec/CrossC2/issues/68#issuecomment-806311359
