### ISSUE TITLE
Windows CS服务器下缺少dll啊。。。编译exe的时候能全用静态库么。。或者把dll丢上来？

### ISSUE THREAD

**Issue by JeremyChiang1992** [gloxec/CrossC2#76]
![图片](https://user-images.githubusercontent.com/17865624/114556196-0c96b780-9c9b-11eb-9408-cdd3db96c8db.png)

**Comment by gloxec** [comment]
release 中的win客户端是附带了dll文件的，以及wiki中注意事项也是附带了dll压缩包下载地址的
https://github.com/gloxec/CrossC2/releases/download/v2.2.1/genCrossC2.Win.zip
