### ISSUE TITLE
cs4.1 mac上线后无法下载

### ISSUE THREAD

**Issue by IC3-CR3AM** [gloxec/CrossC2#77]
下载路径中出现双斜杠，形如：/Downloads//xxxx

**Comment by gloxec** [comment]
很抱歉现在才回复，前期因为环境问题无法进行测试。

测试发现双斜杠是不影响下载的，但可能由于程序本身的加固措施，导致在处理下载操作时，效率过于低下，所以下载速度变慢，但文件是在正常下载的，后续会修复此问题
