### ISSUE TITLE
terminal returned a "[conf]: alive" after run the c2shell

### ISSUE THREAD

**Issue by jashfjsad** [gloxec/CrossC2#78]
after i run the shell generated by gencrossc2.linux(2.2.1),the terminal appeard a"[conf]: alive"like below.
![alive](https://user-images.githubusercontent.com/82137032/115059909-33c8d100-9eb5-11eb-8586-f8dafb12e848.PNG)

env:
cobaltstrike 4.2
ubuntu 18.04

**Comment by gloxec** [comment]
This prompt is to confirm that the beacon can successfully communicate with the teamserver server network. The reason for this is that there is no prompt in the earlier version, but it cannot be started in some environments, and some information needs to be returned to confirm the failure reason.

**Comment by gloxec** [comment]
If it is to replace some native programs of the system to act as a rootkit, the prompt message here is indeed too disturbing.
In the next version, consider adding a parameter option for generating silence or writing error messages to files in other locations.

**Comment by gloxec** [comment]
The [v2.2.5 version](https://github.com/gloxec/CrossC2/releases/tag/v2.2.5) that has been pushed has removed the default prompt, and it will prompt for information unless the environment variable is set to debug mode`export CC_DEBUG=1 ; ./beacon`.
