### ISSUE TITLE
this is not a issue need help 

### ISSUE THREAD

**Issue by ALLERRORr** [gloxec/CrossC2#80]
how to generate playload on windows?

this is a fantastic tools 
or
A Full Documentation

thanks

**Comment by gloxec** [comment]
The usage in the document applies to windows:
1. Download genCrossC2.Win.zip & CrossC2.cna, modify the configuration path in cna.
2. Copy .cobaltstrike.beacon_keys on teamserver to the local.
3. Use the GUI function provided by cna. Or directly call the genCrossC2.Win.exe program in cmd.exe.
