### ISSUE TITLE
cs4.1 CrossC2 能生成Payload 但是无法上线

### ISSUE THREAD

**Issue by ysssysssy** [gloxec/CrossC2#84]
WEB日志能看到去访问服务端了 但是不会返回数据 
![Dingtalk_20210531101626](https://user-images.githubusercontent.com/39210934/120130777-970a8a80-c1f9-11eb-8a05-b890ef215cf8.jpg)

**Comment by ysssysssy** [comment]
服务端
![Dingtalk_20210531103003](https://user-images.githubusercontent.com/39210934/120131527-2f553f00-c1fb-11eb-88b5-888d385d7e07.jpg)

**Comment by gloxec** [comment]
有没有出现`[conf]: alive`的信息提示呢？

**Comment by ysssysssy** [comment]
没有 什么提示也没有

**Comment by gloxec** [comment]
那可能是listener设定的端口无法访问，beacon在运行时，首先会尝试与设定的listener端口建立一次网络连接，如果网络可达的话，是会出现`alive`的提示的

**Comment by ysssysssy** [comment]
是这个的原因吗
![image](https://user-images.githubusercontent.com/39210934/120136135-4a787c80-c204-11eb-84e1-322aab1016bc.png)

**Comment by gloxec** [comment]
listener 是`windows_https`类型的吗,beacon目前强制设定为https

**Comment by ysssysssy** [comment]
是的 https的监听器

**Comment by gloxec** [comment]
netstat中能看到beacon与teamserver通信的记录吗？或者tcpdump抓包查看下是否成功建立过连接以及试试更换监听端口。未出现`[conf]: alive`信息，怀疑可能是beacon所在环境无法访问外部40043端口

**Comment by ysssysssy** [comment]
抓到的包是这样的
![image](https://user-images.githubusercontent.com/39210934/120168965-0b612000-c232-11eb-8dc2-37597dafb18b.png)

**Comment by gloxec** [comment]
经过排查，v2.2.3版本确实存在问题，可使用早期版本或最新的v2.2.4版本 https://github.com/gloxec/CrossC2/releases/tag/v2.2.4
