### ISSUE TITLE
一些linux下出现[error]: parse dll!

### ISSUE THREAD

**Issue by Hanamaki99** [gloxec/CrossC2#85]
请问这个代表什么呢

**Comment by gloxec** [comment]
相似的问题: https://github.com/gloxec/CrossC2/issues/82

出现这个错误的原因有下面几种情况:
1. linux 内核版本较低,以及`/tmp/`或者`./`目录下的读写权限有问题
2. so文件与系统环境不匹配，如编译的so是Linux 64位系统使用的，但目标系统为32位等等。

建议使用[release](https://github.com/gloxec/CrossC2/releases)中最新版本，从`v2.2.2 - stable`版本开始将会详细显示错误具体原因，以及会遍历内置的多种上线方法，及支持`环境变量`或`强制指定`so的上线方法。

**Comment by Hanamaki99** [comment]
OK，换2.2版本出现了这个，另外2.3版本的测试本地都不上线，连alive提示都没有。
[error]: [parse lib]: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/.sys.rrcache.data)!
[error]: [parse lib]: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./.sys.rrcache.data)!
[error]: [parse symbol]: (null)!

**Comment by Hanamaki99** [comment]
是否只支持glibc-2.14版本以上的上线？
另外2.2.3版本本地测试无法正常上线

**Comment by gloxec** [comment]
v2.2.3 版本确实存在问题，已修复 https://github.com/gloxec/CrossC2/releases/tag/v2.2.4

> 是否只支持glibc-2.14版本以上的上线？

beacon本身支持低版本的glibc上线，出现该问题可能是自定义的通讯库编译环境问题，大概率是因为profile.c代码中使用了`memcpy`函数，在编译so时本地的glibc版本较高，导致目标系统无法运行
建议手动实现类似`memcpy`这类glibc高版本会影响的函数，或者在低版本环境上进行编译自定义通讯库。
