### ISSUE TITLE
rebind protocol -> *[error] : read key error

### ISSUE THREAD

**Issue by ogreatary** [gloxec/CrossC2#86]
之前用的好好的。现在突然报错：rebind protocol -> *[error] : read key error
![image](https://user-images.githubusercontent.com/66716610/120969603-ee31d180-c79c-11eb-88ae-d8aa1673d23e.png)

**Comment by gloxec** [comment]
看信息你的key来源于`.cobaltstrike.beacon_keys`，可能是`cs` & `genCrossC2`工作目录与此key文件不在同一目录，所以可以选择将key复制到指定目录，然后在生成beacon时选定到指定的key文件

**Comment by ogreatary** [comment]
这个可以了 得指定目录 不能 ./.coco... 否则找不到
但是有另外一个问题是 在受控端执行命令后，在/tmp/目录下载的二进制文件为0字节 不知道什么原因，当然进程也无法启动

**Comment by gloxec** [comment]
在Attacks->Web Drive-by->Manage中查看下已经部署的web资源，怀疑genCrossC2没有正确生成，所以部署失败或者部署了空文件上去

> 这个可以了 得指定目录 不能 ./.coco... 否则找不到

根据描述，可能是这个原因导致生成失败，因为这里需要指定的是key文件，并非key所在的目录

**Comment by ogreatary** [comment]
不知道为什么 一直部署失败，本地与vps都尝试了

**Comment by ogreatary** [comment]
就是本地都无法生成payload。----

**Comment by gloxec** [comment]
本地运行的报错信息是什么呢？

**Comment by ogreatary** [comment]
我知道为什么了 outputfilename这里必须是完整的物理路径，我直接只是直接写要生成的文件名称就可以 但是这次不知道为什么 必须要得写完整的路径才行 解决了～
