### ISSUE TITLE
/lib/libc.so.6: version `GLIBC_2.7' not found

### ISSUE THREAD

**Issue by Richard-Tang** [gloxec/CrossC2#88]
生成环境: `MacOS Big Sur 11.2.3`

CrossC2版本: `v2.2.4 - stable`

目标环境: `Linux 2.6.18-348.6.1.el5 #1 SMP Tue May 21 15:34:22 EDT 2013 i686 i686 i386 GNU/Linux`

生成命令: `./genCrossC2.MacOS xxx 1333 .cobaltstrike.beacon_keys null Linux-GLIBC x86 ./test`

在目标机器上执行会提示 `./test: /lib/libc.so.6: version 'GLIBC_2.7' not found (required by ./test)`

![image](https://user-images.githubusercontent.com/30547741/121855921-788eae00-cd26-11eb-971f-2466680573ad.png)

**Comment by gloxec** [comment]
请临时使用上一版本 https://github.com/gloxec/CrossC2/releases/tag/v2.2.2
稍后将修复此问题

**Comment by Richard-Tang** [comment]
好的 大哥
