### ISSUE TITLE
cs4.0 linux 端 反斜杠问题

### ISSUE THREAD

**Issue by pinklinux** [gloxec/CrossC2#90]
生成的是 linux 端,正常上线后,访问目录,会显示反斜杠 /www/\wwwroot\ 什么内容都不显示,去掉了\  访问可以正常显示,可能这个只是在 linux 端存在,win 下好像没事.上传文件也一样.无法成功.

**Comment by gloxec** [comment]
这个反斜杠是cs客户端自己添加上去的，beacon端会自己纠正，还没遇到无法上传文件的情况，麻烦贴下Linux uname -a 以及CrossC2版本& CS中文件操作GUI界面信息

**Comment by pinklinux** [comment]
刚才测试了下,上传好像可以,但是删除好像删除不掉,还有 linux 下在文件管理里面,切换目录页无法切换,非要手动把那个反斜杠去掉
<img width="457" alt="image" src="https://user-images.githubusercontent.com/37838492/122701731-72498600-d280-11eb-9019-0666c96cc5c7.png">
<img width="275" alt="image" src="https://user-images.githubusercontent.com/37838492/122701756-8097a200-d280-11eb-8284-5b9a49e5403e.png">
Linux  4.18.0-193.14.2.el8_2.x86_64 #1 SMP Sun Jul 26 03:54:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

CrossC2 v2.0

**Comment by gloxec** [comment]
1.  因为这里cs客户端会自己添加\（为windows设计的原因），所以这里的删除操作beacon忽略了，避免因为符号造成误删影响，所以删除操操作手动shell rm吧
2. 目录页是可以切换的，注意左侧的目录树，数据更新后会在左侧目录树显示，目录树上点击后右侧的文件列表信息即可显示

**Comment by gloxec** [comment]
因为cs的所有操作都是为windows编写的，所以文件目录操作它自己都会前后加反斜杠，beacon端会纠正回传过来的数据，但是cs客户端的展示页面无法更改，造成的影响有:
- : 目录，文件操作自动会添加反斜杠

- : 目录树无法正常工作，即使是子目录下的路径，也会产生新的目录树出来
