### ISSUE TITLE
Cs4.3无法上线

### ISSUE THREAD

**Issue by dwjteam** [gloxec/CrossC2#92]
Payload生成没问题，但无法上线，我修改了cs默认证书和添加c2伪造域名脚本。
执行脚本提示：[conf]alive

**Comment by dwjteam** [comment]
还需要那些地方要注意的吗？

**Comment by gloxec** [comment]
出现[conf]:alive代表可以与c2server建立网络连接，webLog与teamserver有无输出其他信息呢？

**Comment by dwjteam** [comment]
我仅设置ip和端口一样就生成payload,weblog有信息，也没法正常上线，生成payload也没报错，奇怪了，我服务器没防火墙的。> 出现[conf]:alive代表可以与c2server建立网络连接，webLog与teamserver有无输出其他信息呢？

**Comment by 0x594** [comment]
大佬有学习群吗

**Comment by gloxec** [comment]
Weblog输出信息可以贴一下吗？还有teamserver端的信息

**Comment by dwjteam** [comment]
<img width="1056" alt="截屏2021-06-28 下午3 39 22"   src="https://user-images.githubusercontent.com/51328807/123599377-1ce51a00-d828-11eb-86a2-ccc1307a74df.png">
weblog 有信息「Request: GET /load ；Response: 404 Not Found；」，teamserver没信息；./CrossC2-test就报：[conf]: alive
我是服务端生成payload的

**Comment by 9018** [comment]
咱俩一模一样

**Comment by dwjteam** [comment]
> 咱俩一模一样

你的cs版本多少，悲剧都不知怎么使用…

**Comment by gloxec** [comment]
@9018 @0x594 你们应该是配置了c2profile吧，这个load请求是cs默认的请求资源，配置c2profile后所以会404。

使用c2profile的场景参考文档与demo:
https://gloxec.github.io/CrossC2/zh_cn/protocol/

https://github.com/gloxec/CrossC2/blob/cs4.1/protocol_demo/https.profile
https://github.com/gloxec/CrossC2/blob/cs4.1/protocol_demo/c2profile.c

**Comment by 0x594** [comment]
用默认的路由器审计流量很容易检测到阿😭

**Comment by dwjteam** [comment]
@gloxec 感谢大神指点，懂了👍
