### ISSUE TITLE
Linux-bind无法使用

### ISSUE THREAD

**Issue by Richard-Tang** [gloxec/CrossC2#95]
生成linux-bind类型beacon使用的命令如下: ↓↓↓↓↓↓ （这里有个疑问，是不是只需要指定Linux-bind，像前边的ip和port填null就行？）

`./genCrossC2.MacOS 192.168.225.24 1443 cobaltstrike.beacon_keys null Linux-bind x64 ./test2`

`./test2 4444` 正向beacon监听4444端口

`connect 192.168.225.30 4444` 使用session去连接正向`beacon`监听的4444

![image](https://user-images.githubusercontent.com/30547741/126033624-6237fd17-e37f-4ad9-a629-0c0ce8730c46.png)

没有连接成功，并且会导致用来执行`connect`命令的session掉线。

![image](https://user-images.githubusercontent.com/30547741/126033641-28057aec-16c3-4d03-ba35-5fd67389c46d.png)

测试使用的环境均为: `Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

测试过程中未添加使用任何profile

**Comment by gloxec** [comment]
1.生成bind时，ip与port字段无需考虑
2.connect任务做了后台处理应当不会影响到上线的session，例如connect到错误地址，网络连接不通，连接异常终止，连接交互数据持续发生异常等等情况都不会影响到当前session
3.你这里能说下使用的CrossC2版本吗，该功能在cs 3.14时发布后未做过变动，怀疑是cs4.x开始teamserver在connect ip后自动添加:port的行为导致初始化错误。

**Comment by Richard-Tang** [comment]
CrossC2: 2.2.2
Cobaltstrike: 4.1

**Comment by gloxec** [comment]
在`cs4.1 CrossC2: 2.2.4`上经过测试发现Linux-bind是可以正常使用的

> 怀疑是cs4.x开始teamserver在connect ip后自动添加:port的行为导致初始化错误

之前提出的疑似点已排除，`connect ip:port:<default_port_4444>`这种数据依旧可以正确解析并连接到子节点，同时新session命令执行同样正常。

<img width="737" alt="image" src="https://user-images.githubusercontent.com/5158011/127622646-d15a060c-9747-4fd9-b357-7e6303d0dc68.png">

这里有两个问题:
> 1.没有连接成功

是否测试过是防火墙的问题，有无尝试使用nc监听4444端口，查看时候收到数据？

> 2.并且会导致用来执行connect命令的session掉线

尝试使用CrossC2 2.2.4版本，是否存在同样问题？

**Comment by Richard-Tang** [comment]
> 在`cs4.1 CrossC2: 2.2.4`上经过测试发现Linux-bind是可以正常使用的
> 
> > 怀疑是cs4.x开始teamserver在connect ip后自动添加:port的行为导致初始化错误
> 
> 之前提出的疑似点已排除，`connect ip:port:<default_port_4444>`这种数据依旧可以正确解析并连接到子节点，同时新session命令执行同样正常。
> 
> <img alt="image" width="737" src="https://user-images.githubusercontent.com/5158011/127622646-d15a060c-9747-4fd9-b357-7e6303d0dc68.png">
> 
> 这里有两个问题:
> 
> > 1.没有连接成功
> 
> 是否测试过是防火墙的问题，有无尝试使用nc监听4444端口，查看时候收到数据？
> 
> > 2.并且会导致用来执行connect命令的session掉线
> 
> 尝试使用CrossC2 2.2.4版本，是否存在同样问题？

测试了下，在2.2.4版本上确实是可用的。

**Comment by Richard-Tang** [comment]
另外发现个小bug在尝试连接bind时，不加`:`号会导致reverse的beacon掉线。

![image](https://user-images.githubusercontent.com/30547741/127759022-3358930b-c60d-43a6-87bf-a93c8ab3f62d.png)

192.168.225.23连接192.168.225.34的bind端口10033

命令如下

```bash
connect 192.168.225.34 10033
```

![image](https://user-images.githubusercontent.com/30547741/127759061-28fe7f28-88e6-407c-a4d8-5afa88644f70.png)

**Comment by gloxec** [comment]
> 另外发现个小bug在尝试连接bind时，不加:号会导致reverse的beacon掉线

将在下个版本中修复

**Comment by gloxec** [comment]
> 另外发现个小bug在尝试连接bind时，不加:号会导致reverse的beacon掉线

v2.2.5版本已修复该问题
